// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AbandonQuest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AbandonQuest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAbandonQuest(bb:flatbuffers.ByteBuffer, obj?:AbandonQuest):AbandonQuest {
  return (obj || new AbandonQuest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAbandonQuest(bb:flatbuffers.ByteBuffer, obj?:AbandonQuest):AbandonQuest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AbandonQuest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

questId():string|null
questId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAbandonQuest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addQuestId(builder:flatbuffers.Builder, questIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, questIdOffset, 0);
}

static endAbandonQuest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAbandonQuest(builder:flatbuffers.Builder, questIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  AbandonQuest.startAbandonQuest(builder);
  AbandonQuest.addQuestId(builder, questIdOffset);
  return AbandonQuest.endAbandonQuest(builder);
}
}
