// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Accept {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Accept {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAccept(bb:flatbuffers.ByteBuffer, obj?:Accept):Accept {
  return (obj || new Accept()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAccept(bb:flatbuffers.ByteBuffer, obj?:Accept):Accept {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Accept()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

reconnectToken():string|null
reconnectToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
reconnectToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAccept(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addReconnectToken(builder:flatbuffers.Builder, reconnectTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, reconnectTokenOffset, 0);
}

static endAccept(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAccept(builder:flatbuffers.Builder, reconnectTokenOffset:flatbuffers.Offset):flatbuffers.Offset {
  Accept.startAccept(builder);
  Accept.addReconnectToken(builder, reconnectTokenOffset);
  return Accept.endAccept(builder);
}
}
