// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Character } from '../aura-api/character.js';
import { Mob } from '../aura-api/mob.js';
import { Resource } from '../aura-api/resource.js';


export enum AnyEntity {
  NONE = 0,
  Character = 1,
  Mob = 2,
  Resource = 3
}

export function unionToAnyEntity(
  type: AnyEntity,
  accessor: (obj:Character|Mob|Resource) => Character|Mob|Resource|null
): Character|Mob|Resource|null {
  switch(AnyEntity[type]) {
    case 'NONE': return null; 
    case 'Character': return accessor(new Character())! as Character;
    case 'Mob': return accessor(new Mob())! as Mob;
    case 'Resource': return accessor(new Resource())! as Resource;
    default: return null;
  }
}

export function unionListToAnyEntity(
  type: AnyEntity, 
  accessor: (index: number, obj:Character|Mob|Resource) => Character|Mob|Resource|null, 
  index: number
): Character|Mob|Resource|null {
  switch(AnyEntity[type]) {
    case 'NONE': return null; 
    case 'Character': return accessor(index, new Character())! as Character;
    case 'Mob': return accessor(index, new Mob())! as Mob;
    case 'Resource': return accessor(index, new Resource())! as Resource;
    default: return null;
  }
}
