// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AbandonQuest } from '../aura-api/abandon-quest.js';
import { ChatMessage } from '../aura-api/chat-message.js';
import { Cheat } from '../aura-api/cheat.js';
import { Equip } from '../aura-api/equip.js';
import { Input } from '../aura-api/input.js';
import { Interact } from '../aura-api/interact.js';
import { Join } from '../aura-api/join.js';
import { Respawn } from '../aura-api/respawn.js';
import { SpendSkillPoint } from '../aura-api/spend-skill-point.js';


export enum ClientMessageBody {
  NONE = 0,
  Input = 1,
  Join = 2,
  Cheat = 3,
  ChatMessage = 4,
  Equip = 5,
  SpendSkillPoint = 6,
  Respawn = 7,
  Interact = 8,
  AbandonQuest = 9
}

export function unionToClientMessageBody(
  type: ClientMessageBody,
  accessor: (obj:AbandonQuest|ChatMessage|Cheat|Equip|Input|Interact|Join|Respawn|SpendSkillPoint) => AbandonQuest|ChatMessage|Cheat|Equip|Input|Interact|Join|Respawn|SpendSkillPoint|null
): AbandonQuest|ChatMessage|Cheat|Equip|Input|Interact|Join|Respawn|SpendSkillPoint|null {
  switch(ClientMessageBody[type]) {
    case 'NONE': return null; 
    case 'Input': return accessor(new Input())! as Input;
    case 'Join': return accessor(new Join())! as Join;
    case 'Cheat': return accessor(new Cheat())! as Cheat;
    case 'ChatMessage': return accessor(new ChatMessage())! as ChatMessage;
    case 'Equip': return accessor(new Equip())! as Equip;
    case 'SpendSkillPoint': return accessor(new SpendSkillPoint())! as SpendSkillPoint;
    case 'Respawn': return accessor(new Respawn())! as Respawn;
    case 'Interact': return accessor(new Interact())! as Interact;
    case 'AbandonQuest': return accessor(new AbandonQuest())! as AbandonQuest;
    default: return null;
  }
}

export function unionListToClientMessageBody(
  type: ClientMessageBody, 
  accessor: (index: number, obj:AbandonQuest|ChatMessage|Cheat|Equip|Input|Interact|Join|Respawn|SpendSkillPoint) => AbandonQuest|ChatMessage|Cheat|Equip|Input|Interact|Join|Respawn|SpendSkillPoint|null, 
  index: number
): AbandonQuest|ChatMessage|Cheat|Equip|Input|Interact|Join|Respawn|SpendSkillPoint|null {
  switch(ClientMessageBody[type]) {
    case 'NONE': return null; 
    case 'Input': return accessor(index, new Input())! as Input;
    case 'Join': return accessor(index, new Join())! as Join;
    case 'Cheat': return accessor(index, new Cheat())! as Cheat;
    case 'ChatMessage': return accessor(index, new ChatMessage())! as ChatMessage;
    case 'Equip': return accessor(index, new Equip())! as Equip;
    case 'SpendSkillPoint': return accessor(index, new SpendSkillPoint())! as SpendSkillPoint;
    case 'Respawn': return accessor(index, new Respawn())! as Respawn;
    case 'Interact': return accessor(index, new Interact())! as Interact;
    case 'AbandonQuest': return accessor(index, new AbandonQuest())! as AbandonQuest;
    default: return null;
  }
}
