// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ConversationLockKind {
  MinLevel = 0,
  Ascensions = 1,
  QuestAtStage = 2,
  QuestComplete = 3,
  Kills = 4,
  TravelClosed = 5,
  Unknown = 255
}
