// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConversationNode } from '../aura-api/conversation-node.js';


export class Conversation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Conversation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConversation(bb:flatbuffers.ByteBuffer, obj?:Conversation):Conversation {
  return (obj || new Conversation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConversation(bb:flatbuffers.ByteBuffer, obj?:Conversation):Conversation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Conversation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

actorName():string|null
actorName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actorName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

entryNode():string|null
entryNode(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
entryNode(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nodes(index: number, obj?:ConversationNode):ConversationNode|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ConversationNode()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

nodesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startConversation(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addActorName(builder:flatbuffers.Builder, actorNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, actorNameOffset, 0);
}

static addEntryNode(builder:flatbuffers.Builder, entryNodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, entryNodeOffset, 0);
}

static addNodes(builder:flatbuffers.Builder, nodesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nodesOffset, 0);
}

static createNodesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startNodesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endConversation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConversation(builder:flatbuffers.Builder, entityId:bigint, actorNameOffset:flatbuffers.Offset, entryNodeOffset:flatbuffers.Offset, nodesOffset:flatbuffers.Offset):flatbuffers.Offset {
  Conversation.startConversation(builder);
  Conversation.addEntityId(builder, entityId);
  Conversation.addActorName(builder, actorNameOffset);
  Conversation.addEntryNode(builder, entryNodeOffset);
  Conversation.addNodes(builder, nodesOffset);
  return Conversation.endConversation(builder);
}
}
