// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConversationLock } from '../aura-api/conversation-lock.js';


export class ConversationOption {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConversationOption {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConversationOption(bb:flatbuffers.ByteBuffer, obj?:ConversationOption):ConversationOption {
  return (obj || new ConversationOption()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConversationOption(bb:flatbuffers.ByteBuffer, obj?:ConversationOption):ConversationOption {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConversationOption()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

optionIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

grantIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

next():string|null
next(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
next(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

locked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

requiredLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

reply():string|null
reply(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
reply(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

confirmSeconds():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

skillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

travel():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

textId():string|null
textId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
textId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

replyId():string|null
replyId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
replyId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

textKey():string|null
textKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
textKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

replyKey():string|null
replyKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
replyKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

locks(index: number, obj?:ConversationLock):ConversationLock|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new ConversationLock()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

locksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

locksAny():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startConversationOption(builder:flatbuffers.Builder) {
  builder.startObject(16);
}

static addOptionIndex(builder:flatbuffers.Builder, optionIndex:number) {
  builder.addFieldInt8(0, optionIndex, 0);
}

static addGrantIndex(builder:flatbuffers.Builder, grantIndex:number) {
  builder.addFieldInt8(1, grantIndex, 255);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static addNext(builder:flatbuffers.Builder, nextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nextOffset, 0);
}

static addLocked(builder:flatbuffers.Builder, locked:boolean) {
  builder.addFieldInt8(4, +locked, +false);
}

static addRequiredLevel(builder:flatbuffers.Builder, requiredLevel:number) {
  builder.addFieldInt8(5, requiredLevel, 0);
}

static addReply(builder:flatbuffers.Builder, replyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, replyOffset, 0);
}

static addConfirmSeconds(builder:flatbuffers.Builder, confirmSeconds:number) {
  builder.addFieldInt8(7, confirmSeconds, 0);
}

static addSkillId(builder:flatbuffers.Builder, skillId:number) {
  builder.addFieldInt16(8, skillId, 0);
}

static addTravel(builder:flatbuffers.Builder, travel:number) {
  builder.addFieldInt8(9, travel, 0);
}

static addTextId(builder:flatbuffers.Builder, textIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, textIdOffset, 0);
}

static addReplyId(builder:flatbuffers.Builder, replyIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, replyIdOffset, 0);
}

static addTextKey(builder:flatbuffers.Builder, textKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, textKeyOffset, 0);
}

static addReplyKey(builder:flatbuffers.Builder, replyKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, replyKeyOffset, 0);
}

static addLocks(builder:flatbuffers.Builder, locksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, locksOffset, 0);
}

static createLocksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLocksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLocksAny(builder:flatbuffers.Builder, locksAny:boolean) {
  builder.addFieldInt8(15, +locksAny, +false);
}

static endConversationOption(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConversationOption(builder:flatbuffers.Builder, optionIndex:number, grantIndex:number, textOffset:flatbuffers.Offset, nextOffset:flatbuffers.Offset, locked:boolean, requiredLevel:number, replyOffset:flatbuffers.Offset, confirmSeconds:number, skillId:number, travel:number, textIdOffset:flatbuffers.Offset, replyIdOffset:flatbuffers.Offset, textKeyOffset:flatbuffers.Offset, replyKeyOffset:flatbuffers.Offset, locksOffset:flatbuffers.Offset, locksAny:boolean):flatbuffers.Offset {
  ConversationOption.startConversationOption(builder);
  ConversationOption.addOptionIndex(builder, optionIndex);
  ConversationOption.addGrantIndex(builder, grantIndex);
  ConversationOption.addText(builder, textOffset);
  ConversationOption.addNext(builder, nextOffset);
  ConversationOption.addLocked(builder, locked);
  ConversationOption.addRequiredLevel(builder, requiredLevel);
  ConversationOption.addReply(builder, replyOffset);
  ConversationOption.addConfirmSeconds(builder, confirmSeconds);
  ConversationOption.addSkillId(builder, skillId);
  ConversationOption.addTravel(builder, travel);
  ConversationOption.addTextId(builder, textIdOffset);
  ConversationOption.addReplyId(builder, replyIdOffset);
  ConversationOption.addTextKey(builder, textKeyOffset);
  ConversationOption.addReplyKey(builder, replyKeyOffset);
  ConversationOption.addLocks(builder, locksOffset);
  ConversationOption.addLocksAny(builder, locksAny);
  return ConversationOption.endConversationOption(builder);
}
}
