// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ConversationOption {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConversationOption {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConversationOption(bb:flatbuffers.ByteBuffer, obj?:ConversationOption):ConversationOption {
  return (obj || new ConversationOption()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConversationOption(bb:flatbuffers.ByteBuffer, obj?:ConversationOption):ConversationOption {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConversationOption()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

optionIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

grantIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

next():string|null
next(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
next(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

locked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

requiredLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

reply():string|null
reply(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
reply(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

confirmSeconds():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startConversationOption(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addOptionIndex(builder:flatbuffers.Builder, optionIndex:number) {
  builder.addFieldInt8(0, optionIndex, 0);
}

static addGrantIndex(builder:flatbuffers.Builder, grantIndex:number) {
  builder.addFieldInt8(1, grantIndex, 255);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static addNext(builder:flatbuffers.Builder, nextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nextOffset, 0);
}

static addLocked(builder:flatbuffers.Builder, locked:boolean) {
  builder.addFieldInt8(4, +locked, +false);
}

static addRequiredLevel(builder:flatbuffers.Builder, requiredLevel:number) {
  builder.addFieldInt8(5, requiredLevel, 0);
}

static addReply(builder:flatbuffers.Builder, replyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, replyOffset, 0);
}

static addConfirmSeconds(builder:flatbuffers.Builder, confirmSeconds:number) {
  builder.addFieldInt8(7, confirmSeconds, 0);
}

static endConversationOption(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConversationOption(builder:flatbuffers.Builder, optionIndex:number, grantIndex:number, textOffset:flatbuffers.Offset, nextOffset:flatbuffers.Offset, locked:boolean, requiredLevel:number, replyOffset:flatbuffers.Offset, confirmSeconds:number):flatbuffers.Offset {
  ConversationOption.startConversationOption(builder);
  ConversationOption.addOptionIndex(builder, optionIndex);
  ConversationOption.addGrantIndex(builder, grantIndex);
  ConversationOption.addText(builder, textOffset);
  ConversationOption.addNext(builder, nextOffset);
  ConversationOption.addLocked(builder, locked);
  ConversationOption.addRequiredLevel(builder, requiredLevel);
  ConversationOption.addReply(builder, replyOffset);
  ConversationOption.addConfirmSeconds(builder, confirmSeconds);
  return ConversationOption.endConversationOption(builder);
}
}
