// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConversationLockKind } from '../aura-api/conversation-lock-kind.js';


export class ConversationLock {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConversationLock {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConversationLock(bb:flatbuffers.ByteBuffer, obj?:ConversationLock):ConversationLock {
  return (obj || new ConversationLock()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConversationLock(bb:flatbuffers.ByteBuffer, obj?:ConversationLock):ConversationLock {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConversationLock()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():ConversationLockKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ConversationLockKind.Unknown;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

have():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

quest():string|null
quest(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
quest(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

stage():string|null
stage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

species():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startConversationLock(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addKind(builder:flatbuffers.Builder, kind:ConversationLockKind) {
  builder.addFieldInt8(0, kind, ConversationLockKind.Unknown);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(1, value, 0);
}

static addHave(builder:flatbuffers.Builder, have:number) {
  builder.addFieldInt32(2, have, 0);
}

static addQuest(builder:flatbuffers.Builder, questOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, questOffset, 0);
}

static addStage(builder:flatbuffers.Builder, stageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, stageOffset, 0);
}

static addSpecies(builder:flatbuffers.Builder, species:bigint) {
  builder.addFieldInt64(5, species, BigInt('0'));
}

static endConversationLock(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConversationLock(builder:flatbuffers.Builder, kind:ConversationLockKind, value:number, have:number, questOffset:flatbuffers.Offset, stageOffset:flatbuffers.Offset, species:bigint):flatbuffers.Offset {
  ConversationLock.startConversationLock(builder);
  ConversationLock.addKind(builder, kind);
  ConversationLock.addValue(builder, value);
  ConversationLock.addHave(builder, have);
  ConversationLock.addQuest(builder, questOffset);
  ConversationLock.addStage(builder, stageOffset);
  ConversationLock.addSpecies(builder, species);
  return ConversationLock.endConversationLock(builder);
}
}
