// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EffectKind {
  Resist = 1,
  Slow = 2,
  Speed = 4,
  Lifesteal = 8,
  Reflect = 16,
  TickRate = 32,
  Dot = 64,
  Hot = 128,
  Shield = 256,
  Calm = 512,
  Stun = 1024,
  Charm = 2048
}
