// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntityMessageKind } from '../aura-api/entity-message-kind.js';


export class EntityMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityMessage(bb:flatbuffers.ByteBuffer, obj?:EntityMessage):EntityMessage {
  return (obj || new EntityMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityMessage(bb:flatbuffers.ByteBuffer, obj?:EntityMessage):EntityMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

kind():EntityMessageKind {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EntityMessageKind.Chat;
}

static startEntityMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static addKind(builder:flatbuffers.Builder, kind:EntityMessageKind) {
  builder.addFieldInt8(2, kind, EntityMessageKind.Chat);
}

static endEntityMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityMessage(builder:flatbuffers.Builder, entityId:bigint, messageOffset:flatbuffers.Offset, kind:EntityMessageKind):flatbuffers.Offset {
  EntityMessage.startEntityMessage(builder);
  EntityMessage.addEntityId(builder, entityId);
  EntityMessage.addMessage(builder, messageOffset);
  EntityMessage.addKind(builder, kind);
  return EntityMessage.endEntityMessage(builder);
}
}
