// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ActivationRejection } from '../aura-api/activation-rejection.js';
import { Conversation } from '../aura-api/conversation.js';
import { Entity } from '../aura-api/entity.js';
import { Player, unionToPlayer, unionListToPlayer } from '../aura-api/player.js';
import { QuestProgress } from '../aura-api/quest-progress.js';


export class GameState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameState(bb:flatbuffers.ByteBuffer, obj?:GameState):GameState {
  return (obj || new GameState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameState(bb:flatbuffers.ByteBuffer, obj?:GameState):GameState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tick():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

playerType():Player {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Player.NONE;
}

player<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

entities(index: number, obj?:Entity):Entity|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Entity()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

spellbook(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

spellbookLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

spellbookArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

auraSlots(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

auraSlotsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

auraSlotsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

activeAuraSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : -1;
}

spellbookLevels(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

spellbookLevelsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

spellbookLevelsArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

skillPoints():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

passiveSlots(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

passiveSlotsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

passiveSlotsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

cooldownSlots(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

cooldownSlotsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

cooldownSlotsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

cooldownRemainingTicks(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

cooldownRemainingTicksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

cooldownRemainingTicksArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

castSkillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

castTicksLeft():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

castTicksTotal():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

activationRejectedSkillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

activationRejectedReason():ActivationRejection {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ActivationRejection.None;
}

interactableEntityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

conversation(obj?:Conversation):Conversation|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? (obj || new Conversation()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

questProgress(index: number, obj?:QuestProgress):QuestProgress|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? (obj || new QuestProgress()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

questProgressLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

costFactor():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

damageFactor():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

castUtility():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

campCharges():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startGameState(builder:flatbuffers.Builder) {
  builder.startObject(24);
}

static addTick(builder:flatbuffers.Builder, tick:bigint) {
  builder.addFieldInt64(0, tick, BigInt('0'));
}

static addPlayerType(builder:flatbuffers.Builder, playerType:Player) {
  builder.addFieldInt8(1, playerType, Player.NONE);
}

static addPlayer(builder:flatbuffers.Builder, playerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, playerOffset, 0);
}

static addEntities(builder:flatbuffers.Builder, entitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, entitiesOffset, 0);
}

static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSpellbook(builder:flatbuffers.Builder, spellbookOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, spellbookOffset, 0);
}

static createSpellbookVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createSpellbookVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createSpellbookVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startSpellbookVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addAuraSlots(builder:flatbuffers.Builder, auraSlotsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, auraSlotsOffset, 0);
}

static createAuraSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createAuraSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createAuraSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startAuraSlotsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addActiveAuraSlot(builder:flatbuffers.Builder, activeAuraSlot:number) {
  builder.addFieldInt8(6, activeAuraSlot, -1);
}

static addSpellbookLevels(builder:flatbuffers.Builder, spellbookLevelsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, spellbookLevelsOffset, 0);
}

static createSpellbookLevelsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startSpellbookLevelsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addSkillPoints(builder:flatbuffers.Builder, skillPoints:number) {
  builder.addFieldInt16(8, skillPoints, 0);
}

static addPassiveSlots(builder:flatbuffers.Builder, passiveSlotsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, passiveSlotsOffset, 0);
}

static createPassiveSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createPassiveSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createPassiveSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startPassiveSlotsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addCooldownSlots(builder:flatbuffers.Builder, cooldownSlotsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, cooldownSlotsOffset, 0);
}

static createCooldownSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createCooldownSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createCooldownSlotsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startCooldownSlotsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addCooldownRemainingTicks(builder:flatbuffers.Builder, cooldownRemainingTicksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, cooldownRemainingTicksOffset, 0);
}

static createCooldownRemainingTicksVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createCooldownRemainingTicksVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createCooldownRemainingTicksVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startCooldownRemainingTicksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addCastSkillId(builder:flatbuffers.Builder, castSkillId:number) {
  builder.addFieldInt16(12, castSkillId, 0);
}

static addCastTicksLeft(builder:flatbuffers.Builder, castTicksLeft:number) {
  builder.addFieldInt16(13, castTicksLeft, 0);
}

static addCastTicksTotal(builder:flatbuffers.Builder, castTicksTotal:number) {
  builder.addFieldInt16(14, castTicksTotal, 0);
}

static addActivationRejectedSkillId(builder:flatbuffers.Builder, activationRejectedSkillId:number) {
  builder.addFieldInt16(15, activationRejectedSkillId, 0);
}

static addActivationRejectedReason(builder:flatbuffers.Builder, activationRejectedReason:ActivationRejection) {
  builder.addFieldInt8(16, activationRejectedReason, ActivationRejection.None);
}

static addInteractableEntityId(builder:flatbuffers.Builder, interactableEntityId:bigint) {
  builder.addFieldInt64(17, interactableEntityId, BigInt('0'));
}

static addConversation(builder:flatbuffers.Builder, conversationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(18, conversationOffset, 0);
}

static addQuestProgress(builder:flatbuffers.Builder, questProgressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, questProgressOffset, 0);
}

static createQuestProgressVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startQuestProgressVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCostFactor(builder:flatbuffers.Builder, costFactor:number) {
  builder.addFieldFloat32(20, costFactor, 1.0);
}

static addDamageFactor(builder:flatbuffers.Builder, damageFactor:number) {
  builder.addFieldFloat32(21, damageFactor, 1.0);
}

static addCastUtility(builder:flatbuffers.Builder, castUtility:number) {
  builder.addFieldInt8(22, castUtility, 0);
}

static addCampCharges(builder:flatbuffers.Builder, campCharges:number) {
  builder.addFieldInt8(23, campCharges, 0);
}

static endGameState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
