// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum HitKind {
  Damage = 0,
  Crit = 1,
  Heal = 2,
  Absorb = 3,
  Immune = 4
}
