// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Interact {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Interact {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInteract(bb:flatbuffers.ByteBuffer, obj?:Interact):Interact {
  return (obj || new Interact()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInteract(bb:flatbuffers.ByteBuffer, obj?:Interact):Interact {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Interact()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startInteract(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static endInteract(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInteract(builder:flatbuffers.Builder, entityId:bigint):flatbuffers.Offset {
  Interact.startInteract(builder);
  Interact.addEntityId(builder, entityId);
  return Interact.endInteract(builder);
}
}
