// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FogChunk } from '../aura-api/fog-chunk.js';


export class MapFog {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapFog {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapFog(bb:flatbuffers.ByteBuffer, obj?:MapFog):MapFog {
  return (obj || new MapFog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapFog(bb:flatbuffers.ByteBuffer, obj?:MapFog):MapFog {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapFog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cellSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

chunkCells():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

chunks(index: number, obj?:FogChunk):FogChunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new FogChunk()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

chunksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMapFog(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCellSize(builder:flatbuffers.Builder, cellSize:number) {
  builder.addFieldInt8(0, cellSize, 0);
}

static addChunkCells(builder:flatbuffers.Builder, chunkCells:number) {
  builder.addFieldInt8(1, chunkCells, 0);
}

static addChunks(builder:flatbuffers.Builder, chunksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, chunksOffset, 0);
}

static createChunksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChunksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMapFog(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapFog(builder:flatbuffers.Builder, cellSize:number, chunkCells:number, chunksOffset:flatbuffers.Offset):flatbuffers.Offset {
  MapFog.startMapFog(builder);
  MapFog.addCellSize(builder, cellSize);
  MapFog.addChunkCells(builder, chunkCells);
  MapFog.addChunks(builder, chunksOffset);
  return MapFog.endMapFog(builder);
}
}
