// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MessageArgKind {
  Text = 0,
  Number = 1,
  Mob = 2,
  Skill = 3,
  Quest = 4,
  Region = 5,
  List = 6
}
