// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessageArgKind } from '../aura-api/message-arg-kind.js';


export class MessageArg {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MessageArg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMessageArg(bb:flatbuffers.ByteBuffer, obj?:MessageArg):MessageArg {
  return (obj || new MessageArg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMessageArg(bb:flatbuffers.ByteBuffer, obj?:MessageArg):MessageArg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MessageArg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

kind():MessageArgKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessageArgKind.Text;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

number():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

items(index: number):string
items(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
items(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMessageArg(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addKind(builder:flatbuffers.Builder, kind:MessageArgKind) {
  builder.addFieldInt8(1, kind, MessageArgKind.Text);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static addNumber(builder:flatbuffers.Builder, number:number) {
  builder.addFieldFloat64(3, number, 0.0);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(4, id, BigInt('0'));
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMessageArg(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMessageArg(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, kind:MessageArgKind, textOffset:flatbuffers.Offset, number:number, id:bigint, itemsOffset:flatbuffers.Offset):flatbuffers.Offset {
  MessageArg.startMessageArg(builder);
  MessageArg.addName(builder, nameOffset);
  MessageArg.addKind(builder, kind);
  MessageArg.addText(builder, textOffset);
  MessageArg.addNumber(builder, number);
  MessageArg.addId(builder, id);
  MessageArg.addItems(builder, itemsOffset);
  return MessageArg.endMessageArg(builder);
}
}
