// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Obituary {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Obituary {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsObituary(bb:flatbuffers.ByteBuffer, obj?:Obituary):Obituary {
  return (obj || new Obituary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsObituary(bb:flatbuffers.ByteBuffer, obj?:Obituary):Obituary {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Obituary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startObituary(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endObituary(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createObituary(builder:flatbuffers.Builder):flatbuffers.Offset {
  Obituary.startObituary(builder);
  return Obituary.endObituary(builder);
}
}
