// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EffectKind } from '../aura-api/effect-kind.js';


export class OwnEffect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OwnEffect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

skillId():number {
  return this.bb!.readUint16(this.bb_pos);
}

kinds():EffectKind {
  return this.bb!.readUint16(this.bb_pos + 2);
}

totalTicks():number {
  return this.bb!.readUint16(this.bb_pos + 4);
}

caster():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

expiresTick():bigint {
  return this.bb!.readUint64(this.bb_pos + 16);
}

static sizeOf():number {
  return 24;
}

static createOwnEffect(builder:flatbuffers.Builder, skill_id: number, kinds: EffectKind, total_ticks: number, caster: bigint, expires_tick: bigint):flatbuffers.Offset {
  builder.prep(8, 24);
  builder.writeInt64(BigInt(expires_tick ?? 0));
  builder.writeInt64(BigInt(caster ?? 0));
  builder.pad(2);
  builder.writeInt16(total_ticks);
  builder.writeInt16(kinds);
  builder.writeInt16(skill_id);
  return builder.offset();
}

}
