// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RosterEntry } from '../aura-api/roster-entry.js';


export class PlayerRoster {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerRoster {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerRoster(bb:flatbuffers.ByteBuffer, obj?:PlayerRoster):PlayerRoster {
  return (obj || new PlayerRoster()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerRoster(bb:flatbuffers.ByteBuffer, obj?:PlayerRoster):PlayerRoster {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerRoster()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tick():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

entries(index: number, obj?:RosterEntry):RosterEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RosterEntry()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entriesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPlayerRoster(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTick(builder:flatbuffers.Builder, tick:bigint) {
  builder.addFieldInt64(0, tick, BigInt('0'));
}

static addEntries(builder:flatbuffers.Builder, entriesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, entriesOffset, 0);
}

static createEntriesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntriesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPlayerRoster(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerRoster(builder:flatbuffers.Builder, tick:bigint, entriesOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlayerRoster.startPlayerRoster(builder);
  PlayerRoster.addTick(builder, tick);
  PlayerRoster.addEntries(builder, entriesOffset);
  return PlayerRoster.endPlayerRoster(builder);
}
}
