// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum QuestObjectiveKind {
  Kill = 0,
  Harvest = 1,
  TalkTo = 2,
  Reach = 3
}
