// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { QuestObjectiveKind } from '../aura-api/quest-objective-kind.js';


export class QuestObjective {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QuestObjective {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQuestObjective(bb:flatbuffers.ByteBuffer, obj?:QuestObjective):QuestObjective {
  return (obj || new QuestObjective()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQuestObjective(bb:flatbuffers.ByteBuffer, obj?:QuestObjective):QuestObjective {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QuestObjective()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():QuestObjectiveKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : QuestObjectiveKind.Kill;
}

stage():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

target():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

region():string|null
region(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
region(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

n():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

m():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

done():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

trackerKey():string|null
trackerKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
trackerKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startQuestObjective(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addKind(builder:flatbuffers.Builder, kind:QuestObjectiveKind) {
  builder.addFieldInt8(0, kind, QuestObjectiveKind.Kill);
}

static addStage(builder:flatbuffers.Builder, stage:boolean) {
  builder.addFieldInt8(1, +stage, +false);
}

static addTarget(builder:flatbuffers.Builder, target:bigint) {
  builder.addFieldInt64(2, target, BigInt('0'));
}

static addRegion(builder:flatbuffers.Builder, regionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, regionOffset, 0);
}

static addN(builder:flatbuffers.Builder, n:number) {
  builder.addFieldInt32(4, n, 0);
}

static addM(builder:flatbuffers.Builder, m:number) {
  builder.addFieldInt32(5, m, 0);
}

static addDone(builder:flatbuffers.Builder, done:boolean) {
  builder.addFieldInt8(6, +done, +false);
}

static addTrackerKey(builder:flatbuffers.Builder, trackerKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, trackerKeyOffset, 0);
}

static endQuestObjective(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQuestObjective(builder:flatbuffers.Builder, kind:QuestObjectiveKind, stage:boolean, target:bigint, regionOffset:flatbuffers.Offset, n:number, m:number, done:boolean, trackerKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  QuestObjective.startQuestObjective(builder);
  QuestObjective.addKind(builder, kind);
  QuestObjective.addStage(builder, stage);
  QuestObjective.addTarget(builder, target);
  QuestObjective.addRegion(builder, regionOffset);
  QuestObjective.addN(builder, n);
  QuestObjective.addM(builder, m);
  QuestObjective.addDone(builder, done);
  QuestObjective.addTrackerKey(builder, trackerKeyOffset);
  return QuestObjective.endQuestObjective(builder);
}
}
