// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Respawn {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Respawn {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRespawn(bb:flatbuffers.ByteBuffer, obj?:Respawn):Respawn {
  return (obj || new Respawn()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRespawn(bb:flatbuffers.ByteBuffer, obj?:Respawn):Respawn {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Respawn()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRespawn(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRespawn(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRespawn(builder:flatbuffers.Builder):flatbuffers.Offset {
  Respawn.startRespawn(builder);
  return Respawn.endRespawn(builder);
}
}
