// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Respec {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Respec {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRespec(bb:flatbuffers.ByteBuffer, obj?:Respec):Respec {
  return (obj || new Respec()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRespec(bb:flatbuffers.ByteBuffer, obj?:Respec):Respec {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Respec()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRespec(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRespec(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRespec(builder:flatbuffers.Builder):flatbuffers.Offset {
  Respec.startRespec(builder);
  return Respec.endRespec(builder);
}
}
