// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { HitKind } from '../aura-api/hit-kind.js';
import { HitPhase } from '../aura-api/hit-phase.js';


export class SkillEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SkillEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSkillEvent(bb:flatbuffers.ByteBuffer, obj?:SkillEvent):SkillEvent {
  return (obj || new SkillEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSkillEvent(bb:flatbuffers.ByteBuffer, obj?:SkillEvent):SkillEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SkillEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

source():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

victim():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

skillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

amount():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

kind():HitKind {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : HitKind.Damage;
}

fired():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

phase():HitPhase {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : HitPhase.Direct;
}

static startSkillEvent(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addSource(builder:flatbuffers.Builder, source:bigint) {
  builder.addFieldInt64(0, source, BigInt('0'));
}

static addVictim(builder:flatbuffers.Builder, victim:bigint) {
  builder.addFieldInt64(1, victim, BigInt('0'));
}

static addSkillId(builder:flatbuffers.Builder, skillId:number) {
  builder.addFieldInt16(2, skillId, 0);
}

static addAmount(builder:flatbuffers.Builder, amount:number) {
  builder.addFieldInt32(3, amount, 0);
}

static addKind(builder:flatbuffers.Builder, kind:HitKind) {
  builder.addFieldInt8(4, kind, HitKind.Damage);
}

static addFired(builder:flatbuffers.Builder, fired:boolean) {
  builder.addFieldInt8(5, +fired, +false);
}

static addPhase(builder:flatbuffers.Builder, phase:HitPhase) {
  builder.addFieldInt8(6, phase, HitPhase.Direct);
}

static endSkillEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSkillEvent(builder:flatbuffers.Builder, source:bigint, victim:bigint, skillId:number, amount:number, kind:HitKind, fired:boolean, phase:HitPhase):flatbuffers.Offset {
  SkillEvent.startSkillEvent(builder);
  SkillEvent.addSource(builder, source);
  SkillEvent.addVictim(builder, victim);
  SkillEvent.addSkillId(builder, skillId);
  SkillEvent.addAmount(builder, amount);
  SkillEvent.addKind(builder, kind);
  SkillEvent.addFired(builder, fired);
  SkillEvent.addPhase(builder, phase);
  return SkillEvent.endSkillEvent(builder);
}
}
