// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StartFlight {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartFlight {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartFlight(bb:flatbuffers.ByteBuffer, obj?:StartFlight):StartFlight {
  return (obj || new StartFlight()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartFlight(bb:flatbuffers.ByteBuffer, obj?:StartFlight):StartFlight {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartFlight()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

destinationCampfireId():string|null
destinationCampfireId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
destinationCampfireId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStartFlight(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDestinationCampfireId(builder:flatbuffers.Builder, destinationCampfireIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, destinationCampfireIdOffset, 0);
}

static endStartFlight(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStartFlight(builder:flatbuffers.Builder, destinationCampfireIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  StartFlight.startStartFlight(builder);
  StartFlight.addDestinationCampfireId(builder, destinationCampfireIdOffset);
  return StartFlight.endStartFlight(builder);
}
}
