// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { UtilityKind } from '../aura-api/utility-kind.js';


export class UseUtility {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UseUtility {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUseUtility(bb:flatbuffers.ByteBuffer, obj?:UseUtility):UseUtility {
  return (obj || new UseUtility()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUseUtility(bb:flatbuffers.ByteBuffer, obj?:UseUtility):UseUtility {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UseUtility()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():UtilityKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : UtilityKind.None;
}

static startUseUtility(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addKind(builder:flatbuffers.Builder, kind:UtilityKind) {
  builder.addFieldInt8(0, kind, UtilityKind.None);
}

static endUseUtility(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUseUtility(builder:flatbuffers.Builder, kind:UtilityKind):flatbuffers.Offset {
  UseUtility.startUseUtility(builder);
  UseUtility.addKind(builder, kind);
  return UseUtility.endUseUtility(builder);
}
}
