// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum UtilityKind {
  None = 0,
  Recall = 1,
  Camp = 2,
  Ascend = 3
}
