// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import "strconv"

type AuraType byte

const (
	AuraTypeDamage AuraType = 0
	AuraTypeHeal   AuraType = 1
)

var EnumNamesAuraType = map[AuraType]string{
	AuraTypeDamage: "Damage",
	AuraTypeHeal:   "Heal",
}

var EnumValuesAuraType = map[string]AuraType{
	"Damage": AuraTypeDamage,
	"Heal":   AuraTypeHeal,
}

func (v AuraType) String() string {
	if s, ok := EnumNamesAuraType[v]; ok {
		return s
	}
	return "AuraType(" + strconv.FormatInt(int64(v), 10) + ")"
}
