// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Character struct {
	_tab flatbuffers.Table
}

func GetRootAsCharacter(buf []byte, offset flatbuffers.UOffsetT) *Character {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Character{}
	x.Init(buf, n+offset)
	return x
}

func FinishCharacterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCharacter(buf []byte, offset flatbuffers.UOffsetT) *Character {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Character{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCharacterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Character) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Character) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Character) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Character) EntityType() EntityType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return EntityType(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Character) MutateEntityType(n EntityType) bool {
	return rcv._tab.MutateUint16Slot(6, uint16(n))
}

func (rcv *Character) StatusEffects(j int) StatusEffect {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return StatusEffect(rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2)))
	}
	return 0
}

func (rcv *Character) StatusEffectsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Character) MutateStatusEffects(j int, n StatusEffect) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), uint16(n))
	}
	return false
}

func (rcv *Character) Pos(obj *Vec2f) *Vec2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vec2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Character) Radius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(12, n)
}

func (rcv *Character) Rotation() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Character) MutateRotation(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *Character) IsHit() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Character) MutateIsHit(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *Character) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Character) Health() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateHealth(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *Character) LevelProgress() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateLevelProgress(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *Character) Level() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateLevel(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *Character) AuraRadius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateAuraRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(26, n)
}

func (rcv *Character) Aabb(obj *AABB) *AABB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(AABB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Character) ActiveSkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateActiveSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(30, n)
}

func (rcv *Character) BurstRadius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateBurstRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(32, n)
}

func (rcv *Character) DamageTaken() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateDamageTaken(n uint32) bool {
	return rcv._tab.MutateUint32Slot(34, n)
}

func (rcv *Character) HealReceived() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateHealReceived(n uint32) bool {
	return rcv._tab.MutateUint32Slot(36, n)
}

func (rcv *Character) XpGained() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateXpGained(n uint32) bool {
	return rcv._tab.MutateUint32Slot(38, n)
}

func CharacterStart(builder *flatbuffers.Builder) {
	builder.StartObject(18)
}
func CharacterAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func CharacterAddEntityType(builder *flatbuffers.Builder, entityType EntityType) {
	builder.PrependUint16Slot(1, uint16(entityType), 0)
}
func CharacterAddStatusEffects(builder *flatbuffers.Builder, statusEffects flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(statusEffects), 0)
}
func CharacterStartStatusEffectsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func CharacterAddPos(builder *flatbuffers.Builder, pos flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(pos), 0)
}
func CharacterAddRadius(builder *flatbuffers.Builder, radius uint16) {
	builder.PrependUint16Slot(4, radius, 0)
}
func CharacterAddRotation(builder *flatbuffers.Builder, rotation float32) {
	builder.PrependFloat32Slot(5, rotation, 0.0)
}
func CharacterAddIsHit(builder *flatbuffers.Builder, isHit bool) {
	builder.PrependBoolSlot(6, isHit, false)
}
func CharacterAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(name), 0)
}
func CharacterAddHealth(builder *flatbuffers.Builder, health uint32) {
	builder.PrependUint32Slot(8, health, 0)
}
func CharacterAddLevelProgress(builder *flatbuffers.Builder, levelProgress uint32) {
	builder.PrependUint32Slot(9, levelProgress, 0)
}
func CharacterAddLevel(builder *flatbuffers.Builder, level uint32) {
	builder.PrependUint32Slot(10, level, 0)
}
func CharacterAddAuraRadius(builder *flatbuffers.Builder, auraRadius uint16) {
	builder.PrependUint16Slot(11, auraRadius, 0)
}
func CharacterAddAabb(builder *flatbuffers.Builder, aabb flatbuffers.UOffsetT) {
	builder.PrependStructSlot(12, flatbuffers.UOffsetT(aabb), 0)
}
func CharacterAddActiveSkillId(builder *flatbuffers.Builder, activeSkillId uint16) {
	builder.PrependUint16Slot(13, activeSkillId, 0)
}
func CharacterAddBurstRadius(builder *flatbuffers.Builder, burstRadius uint16) {
	builder.PrependUint16Slot(14, burstRadius, 0)
}
func CharacterAddDamageTaken(builder *flatbuffers.Builder, damageTaken uint32) {
	builder.PrependUint32Slot(15, damageTaken, 0)
}
func CharacterAddHealReceived(builder *flatbuffers.Builder, healReceived uint32) {
	builder.PrependUint32Slot(16, healReceived, 0)
}
func CharacterAddXpGained(builder *flatbuffers.Builder, xpGained uint32) {
	builder.PrependUint32Slot(17, xpGained, 0)
}
func CharacterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
