// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Equip struct {
	_tab flatbuffers.Table
}

func GetRootAsEquip(buf []byte, offset flatbuffers.UOffsetT) *Equip {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Equip{}
	x.Init(buf, n+offset)
	return x
}

func FinishEquipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEquip(buf []byte, offset flatbuffers.UOffsetT) *Equip {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Equip{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEquipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Equip) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Equip) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Equip) SkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Equip) MutateSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *Equip) Slot() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Equip) MutateSlot(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func EquipStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EquipAddSkillId(builder *flatbuffers.Builder, skillId uint16) {
	builder.PrependUint16Slot(0, skillId, 0)
}
func EquipAddSlot(builder *flatbuffers.Builder, slot int8) {
	builder.PrependInt8Slot(1, slot, 0)
}
func EquipEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
