// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Respawn struct {
	_tab flatbuffers.Table
}

func GetRootAsRespawn(buf []byte, offset flatbuffers.UOffsetT) *Respawn {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Respawn{}
	x.Init(buf, n+offset)
	return x
}

func FinishRespawnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRespawn(buf []byte, offset flatbuffers.UOffsetT) *Respawn {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Respawn{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRespawnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Respawn) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Respawn) Table() flatbuffers.Table {
	return rcv._tab
}

func RespawnStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RespawnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
