// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AbandonQuest struct {
	_tab flatbuffers.Table
}

func GetRootAsAbandonQuest(buf []byte, offset flatbuffers.UOffsetT) *AbandonQuest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AbandonQuest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAbandonQuestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAbandonQuest(buf []byte, offset flatbuffers.UOffsetT) *AbandonQuest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AbandonQuest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAbandonQuestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AbandonQuest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AbandonQuest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AbandonQuest) QuestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AbandonQuestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AbandonQuestAddQuestId(builder *flatbuffers.Builder, questId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(questId), 0)
}
func AbandonQuestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
