// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Accept struct {
	_tab flatbuffers.Table
}

func GetRootAsAccept(buf []byte, offset flatbuffers.UOffsetT) *Accept {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Accept{}
	x.Init(buf, n+offset)
	return x
}

func FinishAcceptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAccept(buf []byte, offset flatbuffers.UOffsetT) *Accept {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Accept{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAcceptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Accept) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Accept) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Accept) ReconnectToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AcceptStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AcceptAddReconnectToken(builder *flatbuffers.Builder, reconnectToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(reconnectToken), 0)
}
func AcceptEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
