// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type ActivationRejection byte

const (
	ActivationRejectionNone     ActivationRejection = 0
	ActivationRejectionNoAnchor ActivationRejection = 1
	ActivationRejectionNoTarget ActivationRejection = 2
)

var EnumNamesActivationRejection = map[ActivationRejection]string{
	ActivationRejectionNone:     "None",
	ActivationRejectionNoAnchor: "NoAnchor",
	ActivationRejectionNoTarget: "NoTarget",
}

var EnumValuesActivationRejection = map[string]ActivationRejection{
	"None":     ActivationRejectionNone,
	"NoAnchor": ActivationRejectionNoAnchor,
	"NoTarget": ActivationRejectionNoTarget,
}

func (v ActivationRejection) String() string {
	if s, ok := EnumNamesActivationRejection[v]; ok {
		return s
	}
	return "ActivationRejection(" + strconv.FormatInt(int64(v), 10) + ")"
}
