// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConversationLock struct {
	_tab flatbuffers.Table
}

func GetRootAsConversationLock(buf []byte, offset flatbuffers.UOffsetT) *ConversationLock {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConversationLock{}
	x.Init(buf, n+offset)
	return x
}

func FinishConversationLockBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConversationLock(buf []byte, offset flatbuffers.UOffsetT) *ConversationLock {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConversationLock{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConversationLockBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConversationLock) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConversationLock) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConversationLock) Kind() ConversationLockKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ConversationLockKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 255
}

func (rcv *ConversationLock) MutateKind(n ConversationLockKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ConversationLock) Value() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationLock) MutateValue(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *ConversationLock) Have() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationLock) MutateHave(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *ConversationLock) Quest() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationLock) Stage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationLock) Species() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationLock) MutateSpecies(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func ConversationLockStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ConversationLockAddKind(builder *flatbuffers.Builder, kind ConversationLockKind) {
	builder.PrependByteSlot(0, byte(kind), 255)
}
func ConversationLockAddValue(builder *flatbuffers.Builder, value uint32) {
	builder.PrependUint32Slot(1, value, 0)
}
func ConversationLockAddHave(builder *flatbuffers.Builder, have uint32) {
	builder.PrependUint32Slot(2, have, 0)
}
func ConversationLockAddQuest(builder *flatbuffers.Builder, quest flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(quest), 0)
}
func ConversationLockAddStage(builder *flatbuffers.Builder, stage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(stage), 0)
}
func ConversationLockAddSpecies(builder *flatbuffers.Builder, species uint64) {
	builder.PrependUint64Slot(5, species, 0)
}
func ConversationLockEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
