// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConversationOption struct {
	_tab flatbuffers.Table
}

func GetRootAsConversationOption(buf []byte, offset flatbuffers.UOffsetT) *ConversationOption {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConversationOption{}
	x.Init(buf, n+offset)
	return x
}

func FinishConversationOptionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConversationOption(buf []byte, offset flatbuffers.UOffsetT) *ConversationOption {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConversationOption{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConversationOptionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConversationOption) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConversationOption) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConversationOption) OptionIndex() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateOptionIndex(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ConversationOption) GrantIndex() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 255
}

func (rcv *ConversationOption) MutateGrantIndex(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *ConversationOption) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) Next() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) Locked() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ConversationOption) MutateLocked(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ConversationOption) RequiredLevel() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateRequiredLevel(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *ConversationOption) Reply() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConversationOptionStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ConversationOptionAddOptionIndex(builder *flatbuffers.Builder, optionIndex byte) {
	builder.PrependByteSlot(0, optionIndex, 0)
}
func ConversationOptionAddGrantIndex(builder *flatbuffers.Builder, grantIndex byte) {
	builder.PrependByteSlot(1, grantIndex, 255)
}
func ConversationOptionAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(text), 0)
}
func ConversationOptionAddNext(builder *flatbuffers.Builder, next flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(next), 0)
}
func ConversationOptionAddLocked(builder *flatbuffers.Builder, locked bool) {
	builder.PrependBoolSlot(4, locked, false)
}
func ConversationOptionAddRequiredLevel(builder *flatbuffers.Builder, requiredLevel byte) {
	builder.PrependByteSlot(5, requiredLevel, 0)
}
func ConversationOptionAddReply(builder *flatbuffers.Builder, reply flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(reply), 0)
}
func ConversationOptionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
