// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type ConversationLockKind byte

const (
	ConversationLockKindMinLevel      ConversationLockKind = 0
	ConversationLockKindAscensions    ConversationLockKind = 1
	ConversationLockKindQuestAtStage  ConversationLockKind = 2
	ConversationLockKindQuestComplete ConversationLockKind = 3
	ConversationLockKindKills         ConversationLockKind = 4
	ConversationLockKindTravelClosed  ConversationLockKind = 5
	ConversationLockKindUnknown       ConversationLockKind = 255
)

var EnumNamesConversationLockKind = map[ConversationLockKind]string{
	ConversationLockKindMinLevel:      "MinLevel",
	ConversationLockKindAscensions:    "Ascensions",
	ConversationLockKindQuestAtStage:  "QuestAtStage",
	ConversationLockKindQuestComplete: "QuestComplete",
	ConversationLockKindKills:         "Kills",
	ConversationLockKindTravelClosed:  "TravelClosed",
	ConversationLockKindUnknown:       "Unknown",
}

var EnumValuesConversationLockKind = map[string]ConversationLockKind{
	"MinLevel":      ConversationLockKindMinLevel,
	"Ascensions":    ConversationLockKindAscensions,
	"QuestAtStage":  ConversationLockKindQuestAtStage,
	"QuestComplete": ConversationLockKindQuestComplete,
	"Kills":         ConversationLockKindKills,
	"TravelClosed":  ConversationLockKindTravelClosed,
	"Unknown":       ConversationLockKindUnknown,
}

func (v ConversationLockKind) String() string {
	if s, ok := EnumNamesConversationLockKind[v]; ok {
		return s
	}
	return "ConversationLockKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
