// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConversationOption struct {
	_tab flatbuffers.Table
}

func GetRootAsConversationOption(buf []byte, offset flatbuffers.UOffsetT) *ConversationOption {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConversationOption{}
	x.Init(buf, n+offset)
	return x
}

func FinishConversationOptionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConversationOption(buf []byte, offset flatbuffers.UOffsetT) *ConversationOption {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConversationOption{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConversationOptionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConversationOption) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConversationOption) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConversationOption) OptionIndex() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateOptionIndex(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ConversationOption) GrantIndex() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 255
}

func (rcv *ConversationOption) MutateGrantIndex(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *ConversationOption) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) Next() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) Locked() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ConversationOption) MutateLocked(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ConversationOption) RequiredLevel() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateRequiredLevel(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *ConversationOption) Reply() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) ConfirmSeconds() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateConfirmSeconds(n byte) bool {
	return rcv._tab.MutateByteSlot(18, n)
}

func (rcv *ConversationOption) SkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(20, n)
}

func (rcv *ConversationOption) Travel() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConversationOption) MutateTravel(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func (rcv *ConversationOption) TextId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) ReplyId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) TextKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) ReplyKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationOption) Locks(obj *ConversationLock, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ConversationOption) LocksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConversationOption) LocksAny() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ConversationOption) MutateLocksAny(n bool) bool {
	return rcv._tab.MutateBoolSlot(34, n)
}

func ConversationOptionStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func ConversationOptionAddOptionIndex(builder *flatbuffers.Builder, optionIndex byte) {
	builder.PrependByteSlot(0, optionIndex, 0)
}
func ConversationOptionAddGrantIndex(builder *flatbuffers.Builder, grantIndex byte) {
	builder.PrependByteSlot(1, grantIndex, 255)
}
func ConversationOptionAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(text), 0)
}
func ConversationOptionAddNext(builder *flatbuffers.Builder, next flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(next), 0)
}
func ConversationOptionAddLocked(builder *flatbuffers.Builder, locked bool) {
	builder.PrependBoolSlot(4, locked, false)
}
func ConversationOptionAddRequiredLevel(builder *flatbuffers.Builder, requiredLevel byte) {
	builder.PrependByteSlot(5, requiredLevel, 0)
}
func ConversationOptionAddReply(builder *flatbuffers.Builder, reply flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(reply), 0)
}
func ConversationOptionAddConfirmSeconds(builder *flatbuffers.Builder, confirmSeconds byte) {
	builder.PrependByteSlot(7, confirmSeconds, 0)
}
func ConversationOptionAddSkillId(builder *flatbuffers.Builder, skillId uint16) {
	builder.PrependUint16Slot(8, skillId, 0)
}
func ConversationOptionAddTravel(builder *flatbuffers.Builder, travel byte) {
	builder.PrependByteSlot(9, travel, 0)
}
func ConversationOptionAddTextId(builder *flatbuffers.Builder, textId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(textId), 0)
}
func ConversationOptionAddReplyId(builder *flatbuffers.Builder, replyId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(replyId), 0)
}
func ConversationOptionAddTextKey(builder *flatbuffers.Builder, textKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(textKey), 0)
}
func ConversationOptionAddReplyKey(builder *flatbuffers.Builder, replyKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(replyKey), 0)
}
func ConversationOptionAddLocks(builder *flatbuffers.Builder, locks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(locks), 0)
}
func ConversationOptionStartLocksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ConversationOptionAddLocksAny(builder *flatbuffers.Builder, locksAny bool) {
	builder.PrependBoolSlot(15, locksAny, false)
}
func ConversationOptionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
