// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type EffectKind uint32

const (
	EffectKindResist    EffectKind = 1
	EffectKindSlow      EffectKind = 2
	EffectKindSpeed     EffectKind = 4
	EffectKindLifesteal EffectKind = 8
	EffectKindReflect   EffectKind = 16
	EffectKindTickRate  EffectKind = 32
	EffectKindDot       EffectKind = 64
	EffectKindHot       EffectKind = 128
	EffectKindShield    EffectKind = 256
	EffectKindCalm      EffectKind = 512
	EffectKindStun      EffectKind = 1024
	EffectKindCharm     EffectKind = 2048
	EffectKindStatUp    EffectKind = 4096
	EffectKindStatDown  EffectKind = 8192
)

var EnumNamesEffectKind = map[EffectKind]string{
	EffectKindResist:    "Resist",
	EffectKindSlow:      "Slow",
	EffectKindSpeed:     "Speed",
	EffectKindLifesteal: "Lifesteal",
	EffectKindReflect:   "Reflect",
	EffectKindTickRate:  "TickRate",
	EffectKindDot:       "Dot",
	EffectKindHot:       "Hot",
	EffectKindShield:    "Shield",
	EffectKindCalm:      "Calm",
	EffectKindStun:      "Stun",
	EffectKindCharm:     "Charm",
	EffectKindStatUp:    "StatUp",
	EffectKindStatDown:  "StatDown",
}

var EnumValuesEffectKind = map[string]EffectKind{
	"Resist":    EffectKindResist,
	"Slow":      EffectKindSlow,
	"Speed":     EffectKindSpeed,
	"Lifesteal": EffectKindLifesteal,
	"Reflect":   EffectKindReflect,
	"TickRate":  EffectKindTickRate,
	"Dot":       EffectKindDot,
	"Hot":       EffectKindHot,
	"Shield":    EffectKindShield,
	"Calm":      EffectKindCalm,
	"Stun":      EffectKindStun,
	"Charm":     EffectKindCharm,
	"StatUp":    EffectKindStatUp,
	"StatDown":  EffectKindStatDown,
}

func (v EffectKind) String() string {
	if s, ok := EnumNamesEffectKind[v]; ok {
		return s
	}
	return "EffectKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
