// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EntityMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsEntityMessage(buf []byte, offset flatbuffers.UOffsetT) *EntityMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EntityMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishEntityMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEntityMessage(buf []byte, offset flatbuffers.UOffsetT) *EntityMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EntityMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEntityMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EntityMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EntityMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EntityMessage) EntityId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EntityMessage) MutateEntityId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *EntityMessage) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityMessage) Kind() EntityMessageKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return EntityMessageKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EntityMessage) MutateKind(n EntityMessageKind) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *EntityMessage) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityMessage) Args(obj *MessageArg, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EntityMessage) ArgsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EntityMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func EntityMessageAddEntityId(builder *flatbuffers.Builder, entityId uint64) {
	builder.PrependUint64Slot(0, entityId, 0)
}
func EntityMessageAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func EntityMessageAddKind(builder *flatbuffers.Builder, kind EntityMessageKind) {
	builder.PrependByteSlot(2, byte(kind), 0)
}
func EntityMessageAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(key), 0)
}
func EntityMessageAddArgs(builder *flatbuffers.Builder, args flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(args), 0)
}
func EntityMessageStartArgsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EntityMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
