// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type EntityType uint16

const (
	EntityTypeDebugCircle           EntityType = 0
	EntityTypeRoundTree             EntityType = 2
	EntityTypeCharacter             EntityType = 4
	EntityTypeStone                 EntityType = 5
	EntityTypeTotem                 EntityType = 17
	EntityTypeCompanion             EntityType = 19
	EntityTypeCampfire              EntityType = 22
	EntityTypeCorpse                EntityType = 23
	EntityTypeTurnip                EntityType = 24
	EntityTypeHouse                 EntityType = 25
	EntityTypeWolf                  EntityType = 26
	EntityTypeBear                  EntityType = 27
	EntityTypeBoar                  EntityType = 28
	EntityTypeStag                  EntityType = 29
	EntityTypeEliteWolf             EntityType = 30
	EntityTypeBramble               EntityType = 31
	EntityTypeSignpost              EntityType = 32
	EntityTypeHermit                EntityType = 33
	EntityTypeDogNpc                EntityType = 34
	EntityTypeKobold                EntityType = 35
	EntityTypeKoboldRanged          EntityType = 36
	EntityTypeSpider                EntityType = 37
	EntityTypeVenomSpider           EntityType = 38
	EntityTypePoisonPool            EntityType = 39
	EntityTypeRockfall              EntityType = 40
	EntityTypeMiner                 EntityType = 41
	EntityTypeBandit                EntityType = 42
	EntityTypeBanditRanged          EntityType = 43
	EntityTypeBanditHealer          EntityType = 44
	EntityTypeEliteBandit           EntityType = 45
	EntityTypeRallyDrummer          EntityType = 46
	EntityTypeCityGuard             EntityType = 47
	EntityTypeVillageHealer         EntityType = 48
	EntityTypeGateWall              EntityType = 49
	EntityTypeArmySoldier           EntityType = 50
	EntityTypeOrc                   EntityType = 51
	EntityTypeSpikeBarricade        EntityType = 52
	EntityTypeFrontCaptain          EntityType = 53
	EntityTypeOrcWarlord            EntityType = 54
	EntityTypeWarbannerTotem        EntityType = 55
	EntityTypeOrcGrunt              EntityType = 56
	EntityTypeSoldierCompanion      EntityType = 57
	EntityTypeShieldbearerCompanion EntityType = 58
	EntityTypeMedicCompanion        EntityType = 59
	EntityTypeTroll                 EntityType = 60
	EntityTypeBanditPyromancer      EntityType = 61
	EntityTypeFarmer                EntityType = 62
	EntityTypeWanderer              EntityType = 63
	EntityTypeTraveller             EntityType = 64
	EntityTypeTownCrier             EntityType = 65
	EntityTypeGiantSpider           EntityType = 66
	EntityTypeAlphaWolf             EntityType = 67
	EntityTypeMarauder              EntityType = 68
	EntityTypeDireWolf              EntityType = 69
	EntityTypeDireBear              EntityType = 70
	EntityTypeFireElemental         EntityType = 71
	EntityTypeGreaterFireElemental  EntityType = 72
	EntityTypeFireTotem             EntityType = 73
	EntityTypeNpcPlaceholder        EntityType = 74
	EntityTypeCamp                  EntityType = 75
	EntityTypeTombstone             EntityType = 76
)

var EnumNamesEntityType = map[EntityType]string{
	EntityTypeDebugCircle:           "DebugCircle",
	EntityTypeRoundTree:             "RoundTree",
	EntityTypeCharacter:             "Character",
	EntityTypeStone:                 "Stone",
	EntityTypeTotem:                 "Totem",
	EntityTypeCompanion:             "Companion",
	EntityTypeCampfire:              "Campfire",
	EntityTypeCorpse:                "Corpse",
	EntityTypeTurnip:                "Turnip",
	EntityTypeHouse:                 "House",
	EntityTypeWolf:                  "Wolf",
	EntityTypeBear:                  "Bear",
	EntityTypeBoar:                  "Boar",
	EntityTypeStag:                  "Stag",
	EntityTypeEliteWolf:             "EliteWolf",
	EntityTypeBramble:               "Bramble",
	EntityTypeSignpost:              "Signpost",
	EntityTypeHermit:                "Hermit",
	EntityTypeDogNpc:                "DogNpc",
	EntityTypeKobold:                "Kobold",
	EntityTypeKoboldRanged:          "KoboldRanged",
	EntityTypeSpider:                "Spider",
	EntityTypeVenomSpider:           "VenomSpider",
	EntityTypePoisonPool:            "PoisonPool",
	EntityTypeRockfall:              "Rockfall",
	EntityTypeMiner:                 "Miner",
	EntityTypeBandit:                "Bandit",
	EntityTypeBanditRanged:          "BanditRanged",
	EntityTypeBanditHealer:          "BanditHealer",
	EntityTypeEliteBandit:           "EliteBandit",
	EntityTypeRallyDrummer:          "RallyDrummer",
	EntityTypeCityGuard:             "CityGuard",
	EntityTypeVillageHealer:         "VillageHealer",
	EntityTypeGateWall:              "GateWall",
	EntityTypeArmySoldier:           "ArmySoldier",
	EntityTypeOrc:                   "Orc",
	EntityTypeSpikeBarricade:        "SpikeBarricade",
	EntityTypeFrontCaptain:          "FrontCaptain",
	EntityTypeOrcWarlord:            "OrcWarlord",
	EntityTypeWarbannerTotem:        "WarbannerTotem",
	EntityTypeOrcGrunt:              "OrcGrunt",
	EntityTypeSoldierCompanion:      "SoldierCompanion",
	EntityTypeShieldbearerCompanion: "ShieldbearerCompanion",
	EntityTypeMedicCompanion:        "MedicCompanion",
	EntityTypeTroll:                 "Troll",
	EntityTypeBanditPyromancer:      "BanditPyromancer",
	EntityTypeFarmer:                "Farmer",
	EntityTypeWanderer:              "Wanderer",
	EntityTypeTraveller:             "Traveller",
	EntityTypeTownCrier:             "TownCrier",
	EntityTypeGiantSpider:           "GiantSpider",
	EntityTypeAlphaWolf:             "AlphaWolf",
	EntityTypeMarauder:              "Marauder",
	EntityTypeDireWolf:              "DireWolf",
	EntityTypeDireBear:              "DireBear",
	EntityTypeFireElemental:         "FireElemental",
	EntityTypeGreaterFireElemental:  "GreaterFireElemental",
	EntityTypeFireTotem:             "FireTotem",
	EntityTypeNpcPlaceholder:        "NpcPlaceholder",
	EntityTypeCamp:                  "Camp",
	EntityTypeTombstone:             "Tombstone",
}

var EnumValuesEntityType = map[string]EntityType{
	"DebugCircle":           EntityTypeDebugCircle,
	"RoundTree":             EntityTypeRoundTree,
	"Character":             EntityTypeCharacter,
	"Stone":                 EntityTypeStone,
	"Totem":                 EntityTypeTotem,
	"Companion":             EntityTypeCompanion,
	"Campfire":              EntityTypeCampfire,
	"Corpse":                EntityTypeCorpse,
	"Turnip":                EntityTypeTurnip,
	"House":                 EntityTypeHouse,
	"Wolf":                  EntityTypeWolf,
	"Bear":                  EntityTypeBear,
	"Boar":                  EntityTypeBoar,
	"Stag":                  EntityTypeStag,
	"EliteWolf":             EntityTypeEliteWolf,
	"Bramble":               EntityTypeBramble,
	"Signpost":              EntityTypeSignpost,
	"Hermit":                EntityTypeHermit,
	"DogNpc":                EntityTypeDogNpc,
	"Kobold":                EntityTypeKobold,
	"KoboldRanged":          EntityTypeKoboldRanged,
	"Spider":                EntityTypeSpider,
	"VenomSpider":           EntityTypeVenomSpider,
	"PoisonPool":            EntityTypePoisonPool,
	"Rockfall":              EntityTypeRockfall,
	"Miner":                 EntityTypeMiner,
	"Bandit":                EntityTypeBandit,
	"BanditRanged":          EntityTypeBanditRanged,
	"BanditHealer":          EntityTypeBanditHealer,
	"EliteBandit":           EntityTypeEliteBandit,
	"RallyDrummer":          EntityTypeRallyDrummer,
	"CityGuard":             EntityTypeCityGuard,
	"VillageHealer":         EntityTypeVillageHealer,
	"GateWall":              EntityTypeGateWall,
	"ArmySoldier":           EntityTypeArmySoldier,
	"Orc":                   EntityTypeOrc,
	"SpikeBarricade":        EntityTypeSpikeBarricade,
	"FrontCaptain":          EntityTypeFrontCaptain,
	"OrcWarlord":            EntityTypeOrcWarlord,
	"WarbannerTotem":        EntityTypeWarbannerTotem,
	"OrcGrunt":              EntityTypeOrcGrunt,
	"SoldierCompanion":      EntityTypeSoldierCompanion,
	"ShieldbearerCompanion": EntityTypeShieldbearerCompanion,
	"MedicCompanion":        EntityTypeMedicCompanion,
	"Troll":                 EntityTypeTroll,
	"BanditPyromancer":      EntityTypeBanditPyromancer,
	"Farmer":                EntityTypeFarmer,
	"Wanderer":              EntityTypeWanderer,
	"Traveller":             EntityTypeTraveller,
	"TownCrier":             EntityTypeTownCrier,
	"GiantSpider":           EntityTypeGiantSpider,
	"AlphaWolf":             EntityTypeAlphaWolf,
	"Marauder":              EntityTypeMarauder,
	"DireWolf":              EntityTypeDireWolf,
	"DireBear":              EntityTypeDireBear,
	"FireElemental":         EntityTypeFireElemental,
	"GreaterFireElemental":  EntityTypeGreaterFireElemental,
	"FireTotem":             EntityTypeFireTotem,
	"NpcPlaceholder":        EntityTypeNpcPlaceholder,
	"Camp":                  EntityTypeCamp,
	"Tombstone":             EntityTypeTombstone,
}

func (v EntityType) String() string {
	if s, ok := EnumNamesEntityType[v]; ok {
		return s
	}
	return "EntityType(" + strconv.FormatInt(int64(v), 10) + ")"
}
