// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type EntityMessageKind byte

const (
	EntityMessageKindChat    EntityMessageKind = 0
	EntityMessageKindUnlock  EntityMessageKind = 1
	EntityMessageKindJournal EntityMessageKind = 2
)

var EnumNamesEntityMessageKind = map[EntityMessageKind]string{
	EntityMessageKindChat:    "Chat",
	EntityMessageKindUnlock:  "Unlock",
	EntityMessageKindJournal: "Journal",
}

var EnumValuesEntityMessageKind = map[string]EntityMessageKind{
	"Chat":    EntityMessageKindChat,
	"Unlock":  EntityMessageKindUnlock,
	"Journal": EntityMessageKindJournal,
}

func (v EntityMessageKind) String() string {
	if s, ok := EnumNamesEntityMessageKind[v]; ok {
		return s
	}
	return "EntityMessageKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
