// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FogChunk struct {
	_tab flatbuffers.Table
}

func GetRootAsFogChunk(buf []byte, offset flatbuffers.UOffsetT) *FogChunk {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FogChunk{}
	x.Init(buf, n+offset)
	return x
}

func FinishFogChunkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFogChunk(buf []byte, offset flatbuffers.UOffsetT) *FogChunk {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FogChunk{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFogChunkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FogChunk) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FogChunk) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FogChunk) X() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FogChunk) MutateX(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *FogChunk) Y() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FogChunk) MutateY(n int16) bool {
	return rcv._tab.MutateInt16Slot(6, n)
}

func (rcv *FogChunk) Bits(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FogChunk) BitsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FogChunk) BitsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FogChunk) MutateBits(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func FogChunkStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FogChunkAddX(builder *flatbuffers.Builder, x int16) {
	builder.PrependInt16Slot(0, x, 0)
}
func FogChunkAddY(builder *flatbuffers.Builder, y int16) {
	builder.PrependInt16Slot(1, y, 0)
}
func FogChunkAddBits(builder *flatbuffers.Builder, bits flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(bits), 0)
}
func FogChunkStartBitsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FogChunkEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
