// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GameState struct {
	_tab flatbuffers.Table
}

func GetRootAsGameState(buf []byte, offset flatbuffers.UOffsetT) *GameState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GameState{}
	x.Init(buf, n+offset)
	return x
}

func FinishGameStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGameState(buf []byte, offset flatbuffers.UOffsetT) *GameState {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GameState{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGameStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GameState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GameState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GameState) Tick() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateTick(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *GameState) PlayerType() Player {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Player(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GameState) MutatePlayerType(n Player) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *GameState) Player(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *GameState) Entities(obj *Entity, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GameState) EntitiesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) Spellbook(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *GameState) SpellbookLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) MutateSpellbook(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *GameState) AuraSlots(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *GameState) AuraSlotsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) MutateAuraSlots(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *GameState) ActiveAuraSlot() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *GameState) MutateActiveAuraSlot(n int8) bool {
	return rcv._tab.MutateInt8Slot(16, n)
}

func (rcv *GameState) SpellbookLevels(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GameState) SpellbookLevelsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) SpellbookLevelsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GameState) MutateSpellbookLevels(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *GameState) SkillPoints() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateSkillPoints(n uint16) bool {
	return rcv._tab.MutateUint16Slot(20, n)
}

func (rcv *GameState) PassiveSlots(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *GameState) PassiveSlotsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) MutatePassiveSlots(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *GameState) CooldownSlots(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *GameState) CooldownSlotsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) MutateCooldownSlots(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *GameState) CooldownRemainingTicks(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *GameState) CooldownRemainingTicksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) MutateCooldownRemainingTicks(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *GameState) CastSkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateCastSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(28, n)
}

func (rcv *GameState) CastTicksLeft() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateCastTicksLeft(n uint16) bool {
	return rcv._tab.MutateUint16Slot(30, n)
}

func (rcv *GameState) CastTicksTotal() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateCastTicksTotal(n uint16) bool {
	return rcv._tab.MutateUint16Slot(32, n)
}

func (rcv *GameState) ActivationRejectedSkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateActivationRejectedSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(34, n)
}

func (rcv *GameState) ActivationRejectedReason() ActivationRejection {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return ActivationRejection(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GameState) MutateActivationRejectedReason(n ActivationRejection) bool {
	return rcv._tab.MutateByteSlot(36, byte(n))
}

func (rcv *GameState) InteractableEntityId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateInteractableEntityId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(38, n)
}

func (rcv *GameState) Conversation(obj *Conversation) *Conversation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Conversation)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *GameState) QuestProgress(obj *QuestProgress, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GameState) QuestProgressLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameState) CostFactor() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *GameState) MutateCostFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(44, n)
}

func (rcv *GameState) DamageFactor() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *GameState) MutateDamageFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(46, n)
}

func (rcv *GameState) CastUtility() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateCastUtility(n byte) bool {
	return rcv._tab.MutateByteSlot(48, n)
}

func (rcv *GameState) CampCharges() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(50))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameState) MutateCampCharges(n byte) bool {
	return rcv._tab.MutateByteSlot(50, n)
}

func (rcv *GameState) HomeCampfire() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(52))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GameState) DiscoveredCampfires(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(54))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *GameState) DiscoveredCampfiresLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(54))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GameStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(26)
}
func GameStateAddTick(builder *flatbuffers.Builder, tick uint64) {
	builder.PrependUint64Slot(0, tick, 0)
}
func GameStateAddPlayerType(builder *flatbuffers.Builder, playerType Player) {
	builder.PrependByteSlot(1, byte(playerType), 0)
}
func GameStateAddPlayer(builder *flatbuffers.Builder, player flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(player), 0)
}
func GameStateAddEntities(builder *flatbuffers.Builder, entities flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(entities), 0)
}
func GameStateStartEntitiesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GameStateAddSpellbook(builder *flatbuffers.Builder, spellbook flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(spellbook), 0)
}
func GameStateStartSpellbookVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func GameStateAddAuraSlots(builder *flatbuffers.Builder, auraSlots flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(auraSlots), 0)
}
func GameStateStartAuraSlotsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func GameStateAddActiveAuraSlot(builder *flatbuffers.Builder, activeAuraSlot int8) {
	builder.PrependInt8Slot(6, activeAuraSlot, -1)
}
func GameStateAddSpellbookLevels(builder *flatbuffers.Builder, spellbookLevels flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(spellbookLevels), 0)
}
func GameStateStartSpellbookLevelsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GameStateAddSkillPoints(builder *flatbuffers.Builder, skillPoints uint16) {
	builder.PrependUint16Slot(8, skillPoints, 0)
}
func GameStateAddPassiveSlots(builder *flatbuffers.Builder, passiveSlots flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(passiveSlots), 0)
}
func GameStateStartPassiveSlotsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func GameStateAddCooldownSlots(builder *flatbuffers.Builder, cooldownSlots flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(cooldownSlots), 0)
}
func GameStateStartCooldownSlotsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func GameStateAddCooldownRemainingTicks(builder *flatbuffers.Builder, cooldownRemainingTicks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(cooldownRemainingTicks), 0)
}
func GameStateStartCooldownRemainingTicksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func GameStateAddCastSkillId(builder *flatbuffers.Builder, castSkillId uint16) {
	builder.PrependUint16Slot(12, castSkillId, 0)
}
func GameStateAddCastTicksLeft(builder *flatbuffers.Builder, castTicksLeft uint16) {
	builder.PrependUint16Slot(13, castTicksLeft, 0)
}
func GameStateAddCastTicksTotal(builder *flatbuffers.Builder, castTicksTotal uint16) {
	builder.PrependUint16Slot(14, castTicksTotal, 0)
}
func GameStateAddActivationRejectedSkillId(builder *flatbuffers.Builder, activationRejectedSkillId uint16) {
	builder.PrependUint16Slot(15, activationRejectedSkillId, 0)
}
func GameStateAddActivationRejectedReason(builder *flatbuffers.Builder, activationRejectedReason ActivationRejection) {
	builder.PrependByteSlot(16, byte(activationRejectedReason), 0)
}
func GameStateAddInteractableEntityId(builder *flatbuffers.Builder, interactableEntityId uint64) {
	builder.PrependUint64Slot(17, interactableEntityId, 0)
}
func GameStateAddConversation(builder *flatbuffers.Builder, conversation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(18, flatbuffers.UOffsetT(conversation), 0)
}
func GameStateAddQuestProgress(builder *flatbuffers.Builder, questProgress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(19, flatbuffers.UOffsetT(questProgress), 0)
}
func GameStateStartQuestProgressVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GameStateAddCostFactor(builder *flatbuffers.Builder, costFactor float32) {
	builder.PrependFloat32Slot(20, costFactor, 1.0)
}
func GameStateAddDamageFactor(builder *flatbuffers.Builder, damageFactor float32) {
	builder.PrependFloat32Slot(21, damageFactor, 1.0)
}
func GameStateAddCastUtility(builder *flatbuffers.Builder, castUtility byte) {
	builder.PrependByteSlot(22, castUtility, 0)
}
func GameStateAddCampCharges(builder *flatbuffers.Builder, campCharges byte) {
	builder.PrependByteSlot(23, campCharges, 0)
}
func GameStateAddHomeCampfire(builder *flatbuffers.Builder, homeCampfire flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(24, flatbuffers.UOffsetT(homeCampfire), 0)
}
func GameStateAddDiscoveredCampfires(builder *flatbuffers.Builder, discoveredCampfires flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(25, flatbuffers.UOffsetT(discoveredCampfires), 0)
}
func GameStateStartDiscoveredCampfiresVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GameStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
