// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type HitKind byte

const (
	HitKindDamage HitKind = 0
	HitKindCrit   HitKind = 1
	HitKindHeal   HitKind = 2
	HitKindAbsorb HitKind = 3
	HitKindImmune HitKind = 4
)

var EnumNamesHitKind = map[HitKind]string{
	HitKindDamage: "Damage",
	HitKindCrit:   "Crit",
	HitKindHeal:   "Heal",
	HitKindAbsorb: "Absorb",
	HitKindImmune: "Immune",
}

var EnumValuesHitKind = map[string]HitKind{
	"Damage": HitKindDamage,
	"Crit":   HitKindCrit,
	"Heal":   HitKindHeal,
	"Absorb": HitKindAbsorb,
	"Immune": HitKindImmune,
}

func (v HitKind) String() string {
	if s, ok := EnumNamesHitKind[v]; ok {
		return s
	}
	return "HitKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
