// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type HitPhase byte

const (
	HitPhaseDirect  HitPhase = 0
	HitPhaseApplied HitPhase = 1
	HitPhaseTick    HitPhase = 2
)

var EnumNamesHitPhase = map[HitPhase]string{
	HitPhaseDirect:  "Direct",
	HitPhaseApplied: "Applied",
	HitPhaseTick:    "Tick",
}

var EnumValuesHitPhase = map[string]HitPhase{
	"Direct":  HitPhaseDirect,
	"Applied": HitPhaseApplied,
	"Tick":    HitPhaseTick,
}

func (v HitPhase) String() string {
	if s, ok := EnumNamesHitPhase[v]; ok {
		return s
	}
	return "HitPhase(" + strconv.FormatInt(int64(v), 10) + ")"
}
