// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Interact struct {
	_tab flatbuffers.Table
}

func GetRootAsInteract(buf []byte, offset flatbuffers.UOffsetT) *Interact {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Interact{}
	x.Init(buf, n+offset)
	return x
}

func FinishInteractBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInteract(buf []byte, offset flatbuffers.UOffsetT) *Interact {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Interact{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInteractBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Interact) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Interact) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Interact) EntityId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Interact) MutateEntityId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func InteractStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InteractAddEntityId(builder *flatbuffers.Builder, entityId uint64) {
	builder.PrependUint64Slot(0, entityId, 0)
}
func InteractEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
