// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Interact struct {
	_tab flatbuffers.Table
}

func GetRootAsInteract(buf []byte, offset flatbuffers.UOffsetT) *Interact {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Interact{}
	x.Init(buf, n+offset)
	return x
}

func FinishInteractBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInteract(buf []byte, offset flatbuffers.UOffsetT) *Interact {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Interact{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInteractBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Interact) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Interact) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Interact) EntityId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Interact) MutateEntityId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Interact) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Interact) OptionIndex() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 255
}

func (rcv *Interact) MutateOptionIndex(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *Interact) GrantIndex() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 255
}

func (rcv *Interact) MutateGrantIndex(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *Interact) Close() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Interact) MutateClose(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func InteractStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func InteractAddEntityId(builder *flatbuffers.Builder, entityId uint64) {
	builder.PrependUint64Slot(0, entityId, 0)
}
func InteractAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nodeId), 0)
}
func InteractAddOptionIndex(builder *flatbuffers.Builder, optionIndex byte) {
	builder.PrependByteSlot(2, optionIndex, 255)
}
func InteractAddGrantIndex(builder *flatbuffers.Builder, grantIndex byte) {
	builder.PrependByteSlot(3, grantIndex, 255)
}
func InteractAddClose(builder *flatbuffers.Builder, close bool) {
	builder.PrependBoolSlot(4, close, false)
}
func InteractEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
