// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MapFog struct {
	_tab flatbuffers.Table
}

func GetRootAsMapFog(buf []byte, offset flatbuffers.UOffsetT) *MapFog {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MapFog{}
	x.Init(buf, n+offset)
	return x
}

func FinishMapFogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMapFog(buf []byte, offset flatbuffers.UOffsetT) *MapFog {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MapFog{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMapFogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MapFog) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapFog) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MapFog) CellSize() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MapFog) MutateCellSize(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *MapFog) ChunkCells() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MapFog) MutateChunkCells(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *MapFog) Chunks(obj *FogChunk, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MapFog) ChunksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MapFogStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MapFogAddCellSize(builder *flatbuffers.Builder, cellSize byte) {
	builder.PrependByteSlot(0, cellSize, 0)
}
func MapFogAddChunkCells(builder *flatbuffers.Builder, chunkCells byte) {
	builder.PrependByteSlot(1, chunkCells, 0)
}
func MapFogAddChunks(builder *flatbuffers.Builder, chunks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(chunks), 0)
}
func MapFogStartChunksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MapFogEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
