// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageArg struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageArg(buf []byte, offset flatbuffers.UOffsetT) *MessageArg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageArg{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageArgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageArg(buf []byte, offset flatbuffers.UOffsetT) *MessageArg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageArg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageArgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageArg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageArg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageArg) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageArg) Kind() MessageArgKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MessageArgKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MessageArg) MutateKind(n MessageArgKind) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *MessageArg) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageArg) Number() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *MessageArg) MutateNumber(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func (rcv *MessageArg) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageArg) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *MessageArg) Items(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *MessageArg) ItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MessageArgStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func MessageArgAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func MessageArgAddKind(builder *flatbuffers.Builder, kind MessageArgKind) {
	builder.PrependByteSlot(1, byte(kind), 0)
}
func MessageArgAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(text), 0)
}
func MessageArgAddNumber(builder *flatbuffers.Builder, number float64) {
	builder.PrependFloat64Slot(3, number, 0.0)
}
func MessageArgAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(4, id, 0)
}
func MessageArgAddItems(builder *flatbuffers.Builder, items flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(items), 0)
}
func MessageArgStartItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MessageArgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
