// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type MessageArgKind byte

const (
	MessageArgKindText   MessageArgKind = 0
	MessageArgKindNumber MessageArgKind = 1
	MessageArgKindMob    MessageArgKind = 2
	MessageArgKindSkill  MessageArgKind = 3
	MessageArgKindQuest  MessageArgKind = 4
	MessageArgKindRegion MessageArgKind = 5
	MessageArgKindList   MessageArgKind = 6
)

var EnumNamesMessageArgKind = map[MessageArgKind]string{
	MessageArgKindText:   "Text",
	MessageArgKindNumber: "Number",
	MessageArgKindMob:    "Mob",
	MessageArgKindSkill:  "Skill",
	MessageArgKindQuest:  "Quest",
	MessageArgKindRegion: "Region",
	MessageArgKindList:   "List",
}

var EnumValuesMessageArgKind = map[string]MessageArgKind{
	"Text":   MessageArgKindText,
	"Number": MessageArgKindNumber,
	"Mob":    MessageArgKindMob,
	"Skill":  MessageArgKindSkill,
	"Quest":  MessageArgKindQuest,
	"Region": MessageArgKindRegion,
	"List":   MessageArgKindList,
}

func (v MessageArgKind) String() string {
	if s, ok := EnumNamesMessageArgKind[v]; ok {
		return s
	}
	return "MessageArgKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
