// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Mob struct {
	_tab flatbuffers.Table
}

func GetRootAsMob(buf []byte, offset flatbuffers.UOffsetT) *Mob {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Mob{}
	x.Init(buf, n+offset)
	return x
}

func FinishMobBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMob(buf []byte, offset flatbuffers.UOffsetT) *Mob {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Mob{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMobBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Mob) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Mob) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Mob) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Mob) EntityType() EntityType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return EntityType(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Mob) MutateEntityType(n EntityType) bool {
	return rcv._tab.MutateUint16Slot(6, uint16(n))
}

func (rcv *Mob) StatusEffects(j int) StatusEffect {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return StatusEffect(rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2)))
	}
	return 0
}

func (rcv *Mob) StatusEffectsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Mob) MutateStatusEffects(j int, n StatusEffect) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), uint16(n))
	}
	return false
}

func (rcv *Mob) Pos(obj *Vec2f) *Vec2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vec2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Mob) Radius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(12, n)
}

func (rcv *Mob) Rotation() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Mob) MutateRotation(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *Mob) Aabb(obj *AABB) *AABB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(AABB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Mob) Health() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateHealth(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *Mob) MobId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateMobId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(20, n)
}

func (rcv *Mob) BurstRadius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateBurstRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(22, n)
}

func (rcv *Mob) DamageTaken() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateDamageTaken(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *Mob) AuraHitStyle() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateAuraHitStyle(n byte) bool {
	return rcv._tab.MutateByteSlot(26, n)
}

func (rcv *Mob) MaxHealth() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateMaxHealth(n uint32) bool {
	return rcv._tab.MutateUint32Slot(28, n)
}

func (rcv *Mob) AuraRadius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateAuraRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(30, n)
}

func (rcv *Mob) HealReceived() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateHealReceived(n uint32) bool {
	return rcv._tab.MutateUint32Slot(32, n)
}

func (rcv *Mob) LightRadius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateLightRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(34, n)
}

func (rcv *Mob) DwellRadius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateDwellRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(36, n)
}

func (rcv *Mob) CritTaken() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateCritTaken(n uint32) bool {
	return rcv._tab.MutateUint32Slot(38, n)
}

func (rcv *Mob) ShieldHp() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateShieldHp(n uint32) bool {
	return rcv._tab.MutateUint32Slot(40, n)
}

func (rcv *Mob) AuraTickInterval() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateAuraTickInterval(n uint16) bool {
	return rcv._tab.MutateUint16Slot(42, n)
}

func (rcv *Mob) AuraTickPhase() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateAuraTickPhase(n uint16) bool {
	return rcv._tab.MutateUint16Slot(44, n)
}

func (rcv *Mob) AuraCategory() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateAuraCategory(n byte) bool {
	return rcv._tab.MutateByteSlot(46, n)
}

func (rcv *Mob) Tier() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Mob) MutateTier(n byte) bool {
	return rcv._tab.MutateByteSlot(48, n)
}

func MobStart(builder *flatbuffers.Builder) {
	builder.StartObject(23)
}
func MobAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func MobAddEntityType(builder *flatbuffers.Builder, entityType EntityType) {
	builder.PrependUint16Slot(1, uint16(entityType), 0)
}
func MobAddStatusEffects(builder *flatbuffers.Builder, statusEffects flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(statusEffects), 0)
}
func MobStartStatusEffectsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func MobAddPos(builder *flatbuffers.Builder, pos flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(pos), 0)
}
func MobAddRadius(builder *flatbuffers.Builder, radius uint16) {
	builder.PrependUint16Slot(4, radius, 0)
}
func MobAddRotation(builder *flatbuffers.Builder, rotation float32) {
	builder.PrependFloat32Slot(5, rotation, 0.0)
}
func MobAddAabb(builder *flatbuffers.Builder, aabb flatbuffers.UOffsetT) {
	builder.PrependStructSlot(6, flatbuffers.UOffsetT(aabb), 0)
}
func MobAddHealth(builder *flatbuffers.Builder, health uint32) {
	builder.PrependUint32Slot(7, health, 0)
}
func MobAddMobId(builder *flatbuffers.Builder, mobId uint16) {
	builder.PrependUint16Slot(8, mobId, 0)
}
func MobAddBurstRadius(builder *flatbuffers.Builder, burstRadius uint16) {
	builder.PrependUint16Slot(9, burstRadius, 0)
}
func MobAddDamageTaken(builder *flatbuffers.Builder, damageTaken uint32) {
	builder.PrependUint32Slot(10, damageTaken, 0)
}
func MobAddAuraHitStyle(builder *flatbuffers.Builder, auraHitStyle byte) {
	builder.PrependByteSlot(11, auraHitStyle, 0)
}
func MobAddMaxHealth(builder *flatbuffers.Builder, maxHealth uint32) {
	builder.PrependUint32Slot(12, maxHealth, 0)
}
func MobAddAuraRadius(builder *flatbuffers.Builder, auraRadius uint16) {
	builder.PrependUint16Slot(13, auraRadius, 0)
}
func MobAddHealReceived(builder *flatbuffers.Builder, healReceived uint32) {
	builder.PrependUint32Slot(14, healReceived, 0)
}
func MobAddLightRadius(builder *flatbuffers.Builder, lightRadius uint16) {
	builder.PrependUint16Slot(15, lightRadius, 0)
}
func MobAddDwellRadius(builder *flatbuffers.Builder, dwellRadius uint16) {
	builder.PrependUint16Slot(16, dwellRadius, 0)
}
func MobAddCritTaken(builder *flatbuffers.Builder, critTaken uint32) {
	builder.PrependUint32Slot(17, critTaken, 0)
}
func MobAddShieldHp(builder *flatbuffers.Builder, shieldHp uint32) {
	builder.PrependUint32Slot(18, shieldHp, 0)
}
func MobAddAuraTickInterval(builder *flatbuffers.Builder, auraTickInterval uint16) {
	builder.PrependUint16Slot(19, auraTickInterval, 0)
}
func MobAddAuraTickPhase(builder *flatbuffers.Builder, auraTickPhase uint16) {
	builder.PrependUint16Slot(20, auraTickPhase, 0)
}
func MobAddAuraCategory(builder *flatbuffers.Builder, auraCategory byte) {
	builder.PrependByteSlot(21, auraCategory, 0)
}
func MobAddTier(builder *flatbuffers.Builder, tier byte) {
	builder.PrependByteSlot(22, tier, 0)
}
func MobEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
