// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerRoster struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerRoster(buf []byte, offset flatbuffers.UOffsetT) *PlayerRoster {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerRoster{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerRosterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerRoster(buf []byte, offset flatbuffers.UOffsetT) *PlayerRoster {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerRoster{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerRosterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerRoster) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerRoster) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerRoster) Tick() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerRoster) MutateTick(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *PlayerRoster) Entries(obj *RosterEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlayerRoster) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PlayerRosterStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PlayerRosterAddTick(builder *flatbuffers.Builder, tick uint64) {
	builder.PrependUint64Slot(0, tick, 0)
}
func PlayerRosterAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(entries), 0)
}
func PlayerRosterStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlayerRosterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
