// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type QuestObjectiveKind byte

const (
	QuestObjectiveKindKill    QuestObjectiveKind = 0
	QuestObjectiveKindHarvest QuestObjectiveKind = 1
	QuestObjectiveKindTalkTo  QuestObjectiveKind = 2
	QuestObjectiveKindReach   QuestObjectiveKind = 3
)

var EnumNamesQuestObjectiveKind = map[QuestObjectiveKind]string{
	QuestObjectiveKindKill:    "Kill",
	QuestObjectiveKindHarvest: "Harvest",
	QuestObjectiveKindTalkTo:  "TalkTo",
	QuestObjectiveKindReach:   "Reach",
}

var EnumValuesQuestObjectiveKind = map[string]QuestObjectiveKind{
	"Kill":    QuestObjectiveKindKill,
	"Harvest": QuestObjectiveKindHarvest,
	"TalkTo":  QuestObjectiveKindTalkTo,
	"Reach":   QuestObjectiveKindReach,
}

func (v QuestObjectiveKind) String() string {
	if s, ok := EnumNamesQuestObjectiveKind[v]; ok {
		return s
	}
	return "QuestObjectiveKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
