// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QuestObjective struct {
	_tab flatbuffers.Table
}

func GetRootAsQuestObjective(buf []byte, offset flatbuffers.UOffsetT) *QuestObjective {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QuestObjective{}
	x.Init(buf, n+offset)
	return x
}

func FinishQuestObjectiveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsQuestObjective(buf []byte, offset flatbuffers.UOffsetT) *QuestObjective {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QuestObjective{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedQuestObjectiveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *QuestObjective) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QuestObjective) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QuestObjective) Kind() QuestObjectiveKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return QuestObjectiveKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *QuestObjective) MutateKind(n QuestObjectiveKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *QuestObjective) Stage() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QuestObjective) MutateStage(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *QuestObjective) Target() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *QuestObjective) MutateTarget(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *QuestObjective) Region() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *QuestObjective) N() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *QuestObjective) MutateN(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *QuestObjective) M() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *QuestObjective) MutateM(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *QuestObjective) Done() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QuestObjective) MutateDone(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *QuestObjective) TrackerKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func QuestObjectiveStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func QuestObjectiveAddKind(builder *flatbuffers.Builder, kind QuestObjectiveKind) {
	builder.PrependByteSlot(0, byte(kind), 0)
}
func QuestObjectiveAddStage(builder *flatbuffers.Builder, stage bool) {
	builder.PrependBoolSlot(1, stage, false)
}
func QuestObjectiveAddTarget(builder *flatbuffers.Builder, target uint64) {
	builder.PrependUint64Slot(2, target, 0)
}
func QuestObjectiveAddRegion(builder *flatbuffers.Builder, region flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(region), 0)
}
func QuestObjectiveAddN(builder *flatbuffers.Builder, n uint32) {
	builder.PrependUint32Slot(4, n, 0)
}
func QuestObjectiveAddM(builder *flatbuffers.Builder, m uint32) {
	builder.PrependUint32Slot(5, m, 0)
}
func QuestObjectiveAddDone(builder *flatbuffers.Builder, done bool) {
	builder.PrependBoolSlot(6, done, false)
}
func QuestObjectiveAddTrackerKey(builder *flatbuffers.Builder, trackerKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(trackerKey), 0)
}
func QuestObjectiveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
