// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QuestProgress struct {
	_tab flatbuffers.Table
}

func GetRootAsQuestProgress(buf []byte, offset flatbuffers.UOffsetT) *QuestProgress {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QuestProgress{}
	x.Init(buf, n+offset)
	return x
}

func FinishQuestProgressBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsQuestProgress(buf []byte, offset flatbuffers.UOffsetT) *QuestProgress {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QuestProgress{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedQuestProgressBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *QuestProgress) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QuestProgress) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QuestProgress) QuestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *QuestProgress) Stages(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *QuestProgress) StagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *QuestProgress) Completed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QuestProgress) MutateCompleted(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func QuestProgressStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func QuestProgressAddQuestId(builder *flatbuffers.Builder, questId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(questId), 0)
}
func QuestProgressAddStages(builder *flatbuffers.Builder, stages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(stages), 0)
}
func QuestProgressStartStagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func QuestProgressAddCompleted(builder *flatbuffers.Builder, completed bool) {
	builder.PrependBoolSlot(2, completed, false)
}
func QuestProgressEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
