// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Respec struct {
	_tab flatbuffers.Table
}

func GetRootAsRespec(buf []byte, offset flatbuffers.UOffsetT) *Respec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Respec{}
	x.Init(buf, n+offset)
	return x
}

func FinishRespecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRespec(buf []byte, offset flatbuffers.UOffsetT) *Respec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Respec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRespecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Respec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Respec) Table() flatbuffers.Table {
	return rcv._tab
}

func RespecStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RespecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
