// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SkillEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsSkillEvent(buf []byte, offset flatbuffers.UOffsetT) *SkillEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SkillEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishSkillEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSkillEvent(buf []byte, offset flatbuffers.UOffsetT) *SkillEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SkillEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSkillEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SkillEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SkillEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SkillEvent) Source() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SkillEvent) MutateSource(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SkillEvent) Victim() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SkillEvent) MutateVictim(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *SkillEvent) SkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SkillEvent) MutateSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *SkillEvent) Amount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SkillEvent) MutateAmount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *SkillEvent) Kind() HitKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return HitKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SkillEvent) MutateKind(n HitKind) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *SkillEvent) Fired() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SkillEvent) MutateFired(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func SkillEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func SkillEventAddSource(builder *flatbuffers.Builder, source uint64) {
	builder.PrependUint64Slot(0, source, 0)
}
func SkillEventAddVictim(builder *flatbuffers.Builder, victim uint64) {
	builder.PrependUint64Slot(1, victim, 0)
}
func SkillEventAddSkillId(builder *flatbuffers.Builder, skillId uint16) {
	builder.PrependUint16Slot(2, skillId, 0)
}
func SkillEventAddAmount(builder *flatbuffers.Builder, amount uint32) {
	builder.PrependUint32Slot(3, amount, 0)
}
func SkillEventAddKind(builder *flatbuffers.Builder, kind HitKind) {
	builder.PrependByteSlot(4, byte(kind), 0)
}
func SkillEventAddFired(builder *flatbuffers.Builder, fired bool) {
	builder.PrependBoolSlot(5, fired, false)
}
func SkillEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
