// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpendSkillPoint struct {
	_tab flatbuffers.Table
}

func GetRootAsSpendSkillPoint(buf []byte, offset flatbuffers.UOffsetT) *SpendSkillPoint {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpendSkillPoint{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpendSkillPointBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpendSkillPoint(buf []byte, offset flatbuffers.UOffsetT) *SpendSkillPoint {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpendSkillPoint{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpendSkillPointBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SpendSkillPoint) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpendSkillPoint) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpendSkillPoint) SkillId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpendSkillPoint) MutateSkillId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *SpendSkillPoint) Unspend() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SpendSkillPoint) MutateUnspend(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func SpendSkillPointStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SpendSkillPointAddSkillId(builder *flatbuffers.Builder, skillId uint16) {
	builder.PrependUint16Slot(0, skillId, 0)
}
func SpendSkillPointAddUnspend(builder *flatbuffers.Builder, unspend bool) {
	builder.PrependBoolSlot(1, unspend, false)
}
func SpendSkillPointEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
