// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StartFlight struct {
	_tab flatbuffers.Table
}

func GetRootAsStartFlight(buf []byte, offset flatbuffers.UOffsetT) *StartFlight {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StartFlight{}
	x.Init(buf, n+offset)
	return x
}

func FinishStartFlightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStartFlight(buf []byte, offset flatbuffers.UOffsetT) *StartFlight {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StartFlight{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStartFlightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StartFlight) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StartFlight) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StartFlight) DestinationCampfireId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StartFlightStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StartFlightAddDestinationCampfireId(builder *flatbuffers.Builder, destinationCampfireId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(destinationCampfireId), 0)
}
func StartFlightEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
