// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import "strconv"

type StatusEffect uint16

const (
	StatusEffectDamaged        StatusEffect = 0
	StatusEffectRegenerating   StatusEffect = 4
	StatusEffectDamagedAmbient StatusEffect = 5
	StatusEffectBurstFired     StatusEffect = 6
)

var EnumNamesStatusEffect = map[StatusEffect]string{
	StatusEffectDamaged:        "Damaged",
	StatusEffectRegenerating:   "Regenerating",
	StatusEffectDamagedAmbient: "DamagedAmbient",
	StatusEffectBurstFired:     "BurstFired",
}

var EnumValuesStatusEffect = map[string]StatusEffect{
	"Damaged":        StatusEffectDamaged,
	"Regenerating":   StatusEffectRegenerating,
	"DamagedAmbient": StatusEffectDamagedAmbient,
	"BurstFired":     StatusEffectBurstFired,
}

func (v StatusEffect) String() string {
	if s, ok := EnumNamesStatusEffect[v]; ok {
		return s
	}
	return "StatusEffect(" + strconv.FormatInt(int64(v), 10) + ")"
}
