// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AuraApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UseUtility struct {
	_tab flatbuffers.Table
}

func GetRootAsUseUtility(buf []byte, offset flatbuffers.UOffsetT) *UseUtility {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UseUtility{}
	x.Init(buf, n+offset)
	return x
}

func FinishUseUtilityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUseUtility(buf []byte, offset flatbuffers.UOffsetT) *UseUtility {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UseUtility{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUseUtilityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UseUtility) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UseUtility) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UseUtility) Kind() UtilityKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return UtilityKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *UseUtility) MutateKind(n UtilityKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func UseUtilityStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UseUtilityAddKind(builder *flatbuffers.Builder, kind UtilityKind) {
	builder.PrependByteSlot(0, byte(kind), 0)
}
func UseUtilityEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
