<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/tiled/generate-palette.mjs — do not hand-edit. -->
<tileset version="1.10" tiledversion="1.12.2" name="aura-props" tilewidth="800" tileheight="512" tilecount="37" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0" type="AuraProp">
  <properties>
   <property name="auraType" value="Barn"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/barn.svg" width="600" height="400"/>
 </tile>
 <tile id="1" type="AuraProp">
  <properties>
   <property name="auraType" value="Bedroll"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/bedroll.svg" width="40" height="130"/>
 </tile>
 <tile id="2" type="AuraProp">
  <properties>
   <property name="auraType" value="Boulder"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/stone.png" width="256" height="256"/>
 </tile>
 <tile id="3" type="AuraProp">
  <properties>
   <property name="auraType" value="Bridge"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/bridge.svg" width="432" height="168"/>
 </tile>
 <tile id="4" type="AuraProp">
  <properties>
   <property name="auraType" value="BrokenCrate"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/brokenCrate.svg" width="70" height="70"/>
 </tile>
 <tile id="5" type="AuraProp">
  <properties>
   <property name="auraType" value="BrokenFence"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/brokenFence.svg" width="200" height="160"/>
 </tile>
 <tile id="6" type="AuraProp">
  <properties>
   <property name="auraType" value="BurntCart"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/burntCart.svg" width="220" height="130"/>
 </tile>
 <tile id="7" type="AuraProp">
  <properties>
   <property name="auraType" value="Bush"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/bush.svg" width="120" height="120"/>
 </tile>
 <tile id="8" type="AuraProp">
  <properties>
   <property name="auraType" value="Cart"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/cart.svg" width="176" height="100"/>
 </tile>
 <tile id="9" type="AuraProp">
  <properties>
   <property name="auraType" value="CaveMouth"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/caveMouth.svg" width="300" height="240"/>
 </tile>
 <tile id="10" type="AuraProp">
  <properties>
   <property name="auraType" value="Cottage"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/cottage.svg" width="300" height="260"/>
 </tile>
 <tile id="11" type="AuraProp">
  <properties>
   <property name="auraType" value="Crate"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/crate.svg" width="76" height="76"/>
 </tile>
 <tile id="12" type="AuraProp">
  <properties>
   <property name="auraType" value="DeadTree"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/deadTree.svg" width="200" height="200"/>
 </tile>
 <tile id="13" type="AuraProp">
  <properties>
   <property name="auraType" value="FallenLog"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/fallenLog.svg" width="240" height="70"/>
 </tile>
 <tile id="14" type="AuraProp">
  <properties>
   <property name="auraType" value="FencePost"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/fencePost.svg" width="44" height="44"/>
 </tile>
 <tile id="15" type="AuraProp">
  <properties>
   <property name="auraType" value="Fish"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/fish.svg" width="100" height="40"/>
 </tile>
 <tile id="16" type="AuraProp">
  <properties>
   <property name="auraType" value="FishingHut"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/fishingHut.svg" width="270" height="208"/>
 </tile>
 <tile id="17" type="AuraProp">
  <properties>
   <property name="auraType" value="Gate"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/gate.svg" width="200" height="160"/>
 </tile>
 <tile id="18" type="AuraProp">
  <properties>
   <property name="auraType" value="GateWall"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/gateWall.svg" width="92" height="92"/>
 </tile>
 <tile id="19" type="AuraProp">
  <properties>
   <property name="auraType" value="Haystack"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/haystack.svg" width="100" height="100"/>
 </tile>
 <tile id="20" type="AuraProp">
  <properties>
   <property name="auraType" value="House"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/house.svg" width="384" height="284"/>
 </tile>
 <tile id="21" type="AuraProp">
  <properties>
   <property name="auraType" value="Mill"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/mill.svg" width="500" height="400"/>
 </tile>
 <tile id="22" type="AuraProp">
  <properties>
   <property name="auraType" value="NetRack"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/netRack.svg" width="280" height="62"/>
 </tile>
 <tile id="23" type="AuraProp">
  <properties>
   <property name="auraType" value="OakTree"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/oakTree.png" width="512" height="512"/>
 </tile>
 <tile id="24" type="AuraProp">
  <properties>
   <property name="auraType" value="Palisade"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/palisade.svg" width="240" height="44"/>
 </tile>
 <tile id="25" type="AuraProp">
  <properties>
   <property name="auraType" value="PineTree"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/pineTree.png" width="512" height="512"/>
 </tile>
 <tile id="26" type="AuraProp">
  <properties>
   <property name="auraType" value="Rock"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/stone.png" width="256" height="256"/>
 </tile>
 <tile id="27" type="AuraProp">
  <properties>
   <property name="auraType" value="Rowboat"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/rowboat.svg" width="12" height="62"/>
 </tile>
 <tile id="28" type="AuraProp">
  <properties>
   <property name="auraType" value="RuinedHouse"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/ruinedHouse.svg" width="400" height="300"/>
 </tile>
 <tile id="29" type="AuraProp">
  <properties>
   <property name="auraType" value="Shipwreck"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/shipwreck.svg" width="800" height="300"/>
 </tile>
 <tile id="30" type="AuraProp">
  <properties>
   <property name="auraType" value="Stump"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/treeSpot.svg" width="100" height="100"/>
 </tile>
 <tile id="31" type="AuraProp">
  <properties>
   <property name="auraType" value="Tent"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/tent.svg" width="144" height="104"/>
 </tile>
 <tile id="32" type="AuraProp">
  <properties>
   <property name="auraType" value="Tombstone"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/tombstone.svg" width="58" height="19"/>
 </tile>
 <tile id="33" type="AuraProp">
  <properties>
   <property name="auraType" value="Torch"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/torch.svg" width="100" height="100"/>
 </tile>
 <tile id="34" type="AuraProp">
  <properties>
   <property name="auraType" value="Tree"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/roundTree.png" width="512" height="512"/>
 </tile>
 <tile id="35" type="AuraProp">
  <properties>
   <property name="auraType" value="Well"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/well.svg" width="100" height="100"/>
 </tile>
 <tile id="36" type="AuraProp">
  <properties>
   <property name="auraType" value="WreckDebris"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/wreckDebris.svg" width="120" height="18"/>
 </tile>
</tileset>
