<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/tiled/generate-palette.mjs — do not hand-edit. -->
<tileset version="1.10" tiledversion="1.12.2" name="aura-props" tilewidth="512" tileheight="512" tilecount="5" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0" type="AuraProp">
  <properties>
   <property name="auraType" value="Boulder"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/stone.png" width="256" height="256"/>
 </tile>
 <tile id="1" type="AuraProp">
  <properties>
   <property name="auraType" value="GateWall"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/gateWall.svg" width="92" height="92"/>
 </tile>
 <tile id="2" type="AuraProp">
  <properties>
   <property name="auraType" value="House"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/house.svg" width="384" height="284"/>
 </tile>
 <tile id="3" type="AuraProp">
  <properties>
   <property name="auraType" value="Rock"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/stone.png" width="256" height="256"/>
 </tile>
 <tile id="4" type="AuraProp">
  <properties>
   <property name="auraType" value="Tree"/>
  </properties>
  <image source="../../../frontend/src/features/game-objects/assets/resources/roundTree.png" width="512" height="512"/>
 </tile>
</tileset>
