<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/tiled/generate-palette.mjs — do not hand-edit. -->
<tileset version="1.10" tiledversion="1.12.2" name="aura-terrain" tilewidth="256" tileheight="256" tilecount="16" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Dark Green Grass 1"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/darkGrass1.svg" width="100" height="100"/>
 </tile>
 <tile id="1" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Dark Green Grass 2"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/darkGrass2.svg" width="100" height="100"/>
 </tile>
 <tile id="2" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Green Grass 1"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/grass1.svg" width="100" height="100"/>
 </tile>
 <tile id="3" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Green Grass 2"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/grass2.svg" width="100" height="100"/>
 </tile>
 <tile id="4" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Dark Stone Patch"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/darkStonePatch.svg" width="100" height="100"/>
 </tile>
 <tile id="5" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Stone Patch"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/stonePatch.svg" width="100" height="100"/>
 </tile>
 <tile id="6" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Pebble"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/pebble.svg" width="100" height="100"/>
 </tile>
 <tile id="7" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Dark Pebble"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/darkPebble.svg" width="100" height="100"/>
 </tile>
 <tile id="8" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Rubble"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/rubble.svg" width="100" height="100"/>
 </tile>
 <tile id="9" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Dark Rubble"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/darkRubble.svg" width="100" height="100"/>
 </tile>
 <tile id="10" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Puddle"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/puddle.svg" width="100" height="100"/>
 </tile>
 <tile id="11" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Dark Puddle"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/darkPuddle.svg" width="100" height="100"/>
 </tile>
 <tile id="12" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Flowers"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/flowers.png" width="256" height="256"/>
 </tile>
 <tile id="13" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Leaves"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/leaves.svg" width="100" height="100"/>
 </tile>
 <tile id="14" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Sand"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/sand1.png" width="256" height="256"/>
 </tile>
 <tile id="15" type="AuraTerrain">
  <properties>
   <property name="auraType" value="Land"/>
  </properties>
  <image source="../../../frontend/src/features/ground-textures/assets/textures/land1.svg" width="100" height="100"/>
 </tile>
</tileset>
