// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec2f } from '../berryhunter-api/vec2f.js';


export class AABB {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AABB {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

lower(obj?:Vec2f):Vec2f|null {
  return (obj || new Vec2f()).__init(this.bb_pos, this.bb!);
}

upper(obj?:Vec2f):Vec2f|null {
  return (obj || new Vec2f()).__init(this.bb_pos + 8, this.bb!);
}

static sizeOf():number {
  return 16;
}

static createAABB(builder:flatbuffers.Builder, lower_x: number, lower_y: number, upper_x: number, upper_y: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.prep(4, 8);
  builder.writeFloat32(upper_y);
  builder.writeFloat32(upper_x);
  builder.prep(4, 8);
  builder.writeFloat32(lower_y);
  builder.writeFloat32(lower_x);
  return builder.offset();
}

}
