// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Accept {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Accept {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAccept(bb:flatbuffers.ByteBuffer, obj?:Accept):Accept {
  return (obj || new Accept()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAccept(bb:flatbuffers.ByteBuffer, obj?:Accept):Accept {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Accept()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startAccept(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endAccept(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAccept(builder:flatbuffers.Builder):flatbuffers.Offset {
  Accept.startAccept(builder);
  return Accept.endAccept(builder);
}
}
