// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ActionType {
  Primary = 0,
  CraftItem = 1,
  EquipItem = 2,
  UnequipItem = 3,
  DropItem = 4,
  PlaceItem = 5,
  ConsumeItem = 6
}
