// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ActionType } from '../berryhunter-api/action-type.js';


export class Action {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Action {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAction(bb:flatbuffers.ByteBuffer, obj?:Action):Action {
  return (obj || new Action()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAction(bb:flatbuffers.ByteBuffer, obj?:Action):Action {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Action()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

item():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

actionType():ActionType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ActionType.Primary;
}

static startAction(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addItem(builder:flatbuffers.Builder, item:number) {
  builder.addFieldInt8(0, item, 0);
}

static addActionType(builder:flatbuffers.Builder, actionType:ActionType) {
  builder.addFieldInt8(1, actionType, ActionType.Primary);
}

static endAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAction(builder:flatbuffers.Builder, item:number, actionType:ActionType):flatbuffers.Offset {
  Action.startAction(builder);
  Action.addItem(builder, item);
  Action.addActionType(builder, actionType);
  return Action.endAction(builder);
}
}
