// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Character } from '../berryhunter-api/character.js';
import { Mob } from '../berryhunter-api/mob.js';
import { Placeable } from '../berryhunter-api/placeable.js';
import { Resource } from '../berryhunter-api/resource.js';


export enum AnyEntity {
  NONE = 0,
  Character = 1,
  Mob = 2,
  Resource = 3,
  Placeable = 4
}

export function unionToAnyEntity(
  type: AnyEntity,
  accessor: (obj:Character|Mob|Placeable|Resource) => Character|Mob|Placeable|Resource|null
): Character|Mob|Placeable|Resource|null {
  switch(AnyEntity[type]) {
    case 'NONE': return null; 
    case 'Character': return accessor(new Character())! as Character;
    case 'Mob': return accessor(new Mob())! as Mob;
    case 'Resource': return accessor(new Resource())! as Resource;
    case 'Placeable': return accessor(new Placeable())! as Placeable;
    default: return null;
  }
}

export function unionListToAnyEntity(
  type: AnyEntity, 
  accessor: (index: number, obj:Character|Mob|Placeable|Resource) => Character|Mob|Placeable|Resource|null, 
  index: number
): Character|Mob|Placeable|Resource|null {
  switch(AnyEntity[type]) {
    case 'NONE': return null; 
    case 'Character': return accessor(index, new Character())! as Character;
    case 'Mob': return accessor(index, new Mob())! as Mob;
    case 'Resource': return accessor(index, new Resource())! as Resource;
    case 'Placeable': return accessor(index, new Placeable())! as Placeable;
    default: return null;
  }
}
