// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AABB } from '../berryhunter-api/aabb.js';
import { EntityType } from '../berryhunter-api/entity-type.js';
import { StatusEffect } from '../berryhunter-api/status-effect.js';
import { Vec2f } from '../berryhunter-api/vec2f.js';


export class Character {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Character {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCharacter(bb:flatbuffers.ByteBuffer, obj?:Character):Character {
  return (obj || new Character()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCharacter(bb:flatbuffers.ByteBuffer, obj?:Character):Character {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Character()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

entityType():EntityType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : EntityType.DebugCircle;
}

statusEffects(index: number):StatusEffect|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

statusEffectsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

statusEffectsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

pos(obj?:Vec2f):Vec2f|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec2f()).__init(this.bb_pos + offset, this.bb!) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

rotation():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

isHit():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

health():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

levelProgress():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

auraRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

aabb(obj?:AABB):AABB|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new AABB()).__init(this.bb_pos + offset, this.bb!) : null;
}

activeSkillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

burstRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

damageTaken():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

healReceived():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

xpGained():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

auraHitStyle():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

maxHealth():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

xpInLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

xpForNextLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

lightRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

campfireBound():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

critTaken():number {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

shieldHp():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

inCombat():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

auraTickInterval():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

auraTickPhase():number {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startCharacter(builder:flatbuffers.Builder) {
  builder.startObject(29);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addEntityType(builder:flatbuffers.Builder, entityType:EntityType) {
  builder.addFieldInt16(1, entityType, EntityType.DebugCircle);
}

static addStatusEffects(builder:flatbuffers.Builder, statusEffectsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, statusEffectsOffset, 0);
}

static createStatusEffectsVector(builder:flatbuffers.Builder, data:StatusEffect[]):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startStatusEffectsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addPos(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, posOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldInt16(4, radius, 0);
}

static addRotation(builder:flatbuffers.Builder, rotation:number) {
  builder.addFieldFloat32(5, rotation, 0.0);
}

static addIsHit(builder:flatbuffers.Builder, isHit:boolean) {
  builder.addFieldInt8(6, +isHit, +false);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, nameOffset, 0);
}

static addHealth(builder:flatbuffers.Builder, health:number) {
  builder.addFieldInt32(8, health, 0);
}

static addLevelProgress(builder:flatbuffers.Builder, levelProgress:number) {
  builder.addFieldInt32(9, levelProgress, 0);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(10, level, 0);
}

static addAuraRadius(builder:flatbuffers.Builder, auraRadius:number) {
  builder.addFieldInt16(11, auraRadius, 0);
}

static addAabb(builder:flatbuffers.Builder, aabbOffset:flatbuffers.Offset) {
  builder.addFieldStruct(12, aabbOffset, 0);
}

static addActiveSkillId(builder:flatbuffers.Builder, activeSkillId:number) {
  builder.addFieldInt16(13, activeSkillId, 0);
}

static addBurstRadius(builder:flatbuffers.Builder, burstRadius:number) {
  builder.addFieldInt16(14, burstRadius, 0);
}

static addDamageTaken(builder:flatbuffers.Builder, damageTaken:number) {
  builder.addFieldInt32(15, damageTaken, 0);
}

static addHealReceived(builder:flatbuffers.Builder, healReceived:number) {
  builder.addFieldInt32(16, healReceived, 0);
}

static addXpGained(builder:flatbuffers.Builder, xpGained:number) {
  builder.addFieldInt32(17, xpGained, 0);
}

static addAuraHitStyle(builder:flatbuffers.Builder, auraHitStyle:number) {
  builder.addFieldInt8(18, auraHitStyle, 0);
}

static addMaxHealth(builder:flatbuffers.Builder, maxHealth:number) {
  builder.addFieldInt32(19, maxHealth, 0);
}

static addXpInLevel(builder:flatbuffers.Builder, xpInLevel:number) {
  builder.addFieldInt32(20, xpInLevel, 0);
}

static addXpForNextLevel(builder:flatbuffers.Builder, xpForNextLevel:number) {
  builder.addFieldInt32(21, xpForNextLevel, 0);
}

static addLightRadius(builder:flatbuffers.Builder, lightRadius:number) {
  builder.addFieldInt16(22, lightRadius, 0);
}

static addCampfireBound(builder:flatbuffers.Builder, campfireBound:boolean) {
  builder.addFieldInt8(23, +campfireBound, +false);
}

static addCritTaken(builder:flatbuffers.Builder, critTaken:number) {
  builder.addFieldInt32(24, critTaken, 0);
}

static addShieldHp(builder:flatbuffers.Builder, shieldHp:number) {
  builder.addFieldInt32(25, shieldHp, 0);
}

static addInCombat(builder:flatbuffers.Builder, inCombat:boolean) {
  builder.addFieldInt8(26, +inCombat, +false);
}

static addAuraTickInterval(builder:flatbuffers.Builder, auraTickInterval:number) {
  builder.addFieldInt16(27, auraTickInterval, 0);
}

static addAuraTickPhase(builder:flatbuffers.Builder, auraTickPhase:number) {
  builder.addFieldInt16(28, auraTickPhase, 0);
}

static endCharacter(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
