// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AABB } from '../berryhunter-api/aabb.js';
import { AuraType } from '../berryhunter-api/aura-type.js';
import { EntityType } from '../berryhunter-api/entity-type.js';
import { OngoingAction } from '../berryhunter-api/ongoing-action.js';
import { StatusEffect } from '../berryhunter-api/status-effect.js';
import { Vec2f } from '../berryhunter-api/vec2f.js';


export class Character {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Character {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCharacter(bb:flatbuffers.ByteBuffer, obj?:Character):Character {
  return (obj || new Character()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCharacter(bb:flatbuffers.ByteBuffer, obj?:Character):Character {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Character()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

entityType():EntityType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : EntityType.DebugCircle;
}

statusEffects(index: number):StatusEffect|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

statusEffectsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

statusEffectsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

pos(obj?:Vec2f):Vec2f|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec2f()).__init(this.bb_pos + offset, this.bb!) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

rotation():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

isHit():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

currentAction(obj?:OngoingAction):OngoingAction|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new OngoingAction()).__init(this.bb_pos + offset, this.bb!) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

equipment(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

equipmentLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

equipmentArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

health():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

satiety():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

bodyTemperature():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

auraRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

activeAura():AuraType {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AuraType.Damage;
}

aabb(obj?:AABB):AABB|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? (obj || new AABB()).__init(this.bb_pos + offset, this.bb!) : null;
}

activeSkillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startCharacter(builder:flatbuffers.Builder) {
  builder.startObject(17);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addEntityType(builder:flatbuffers.Builder, entityType:EntityType) {
  builder.addFieldInt16(1, entityType, EntityType.DebugCircle);
}

static addStatusEffects(builder:flatbuffers.Builder, statusEffectsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, statusEffectsOffset, 0);
}

static createStatusEffectsVector(builder:flatbuffers.Builder, data:StatusEffect[]):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startStatusEffectsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addPos(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, posOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldInt16(4, radius, 0);
}

static addRotation(builder:flatbuffers.Builder, rotation:number) {
  builder.addFieldFloat32(5, rotation, 0.0);
}

static addIsHit(builder:flatbuffers.Builder, isHit:boolean) {
  builder.addFieldInt8(6, +isHit, +false);
}

static addCurrentAction(builder:flatbuffers.Builder, currentActionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, currentActionOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, nameOffset, 0);
}

static addEquipment(builder:flatbuffers.Builder, equipmentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, equipmentOffset, 0);
}

static createEquipmentVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startEquipmentVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addHealth(builder:flatbuffers.Builder, health:number) {
  builder.addFieldInt32(10, health, 0);
}

static addSatiety(builder:flatbuffers.Builder, satiety:number) {
  builder.addFieldInt32(11, satiety, 0);
}

static addBodyTemperature(builder:flatbuffers.Builder, bodyTemperature:number) {
  builder.addFieldInt32(12, bodyTemperature, 0);
}

static addAuraRadius(builder:flatbuffers.Builder, auraRadius:number) {
  builder.addFieldInt16(13, auraRadius, 0);
}

static addActiveAura(builder:flatbuffers.Builder, activeAura:AuraType) {
  builder.addFieldInt8(14, activeAura, AuraType.Damage);
}

static addAabb(builder:flatbuffers.Builder, aabbOffset:flatbuffers.Offset) {
  builder.addFieldStruct(15, aabbOffset, 0);
}

static addActiveSkillId(builder:flatbuffers.Builder, activeSkillId:number) {
  builder.addFieldInt16(16, activeSkillId, 0);
}

static endCharacter(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
