// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ClientMessageBody, unionToClientMessageBody, unionListToClientMessageBody } from '../berryhunter-api/client-message-body.js';


export class ClientMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientMessage(bb:flatbuffers.ByteBuffer, obj?:ClientMessage):ClientMessage {
  return (obj || new ClientMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientMessage(bb:flatbuffers.ByteBuffer, obj?:ClientMessage):ClientMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bodyType():ClientMessageBody {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ClientMessageBody.NONE;
}

body<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startClientMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBodyType(builder:flatbuffers.Builder, bodyType:ClientMessageBody) {
  builder.addFieldInt8(0, bodyType, ClientMessageBody.NONE);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bodyOffset, 0);
}

static endClientMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClientMessage(builder:flatbuffers.Builder, bodyType:ClientMessageBody, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientMessage.startClientMessage(builder);
  ClientMessage.addBodyType(builder, bodyType);
  ClientMessage.addBody(builder, bodyOffset);
  return ClientMessage.endClientMessage(builder);
}
}
