// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EntityType {
  DebugCircle = 0,
  Border = 1,
  RoundTree = 2,
  MarioTree = 3,
  Character = 4,
  Stone = 5,
  Bronze = 6,
  Iron = 7,
  BerryBush = 8,
  Dodo = 9,
  SaberToothCat = 10,
  Mammoth = 11,
  Placeable = 12,
  Titanium = 13,
  Flower = 14,
  AngryMammoth = 15,
  TitaniumShard = 16
}
