// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Equip {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Equip {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEquip(bb:flatbuffers.ByteBuffer, obj?:Equip):Equip {
  return (obj || new Equip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEquip(bb:flatbuffers.ByteBuffer, obj?:Equip):Equip {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Equip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

skillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

slot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

static startEquip(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSkillId(builder:flatbuffers.Builder, skillId:number) {
  builder.addFieldInt16(0, skillId, 0);
}

static addSlot(builder:flatbuffers.Builder, slot:number) {
  builder.addFieldInt8(1, slot, 0);
}

static endEquip(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEquip(builder:flatbuffers.Builder, skillId:number, slot:number):flatbuffers.Offset {
  Equip.startEquip(builder);
  Equip.addSkillId(builder, skillId);
  Equip.addSlot(builder, slot);
  return Equip.endEquip(builder);
}
}
