// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Action } from '../berryhunter-api/action.js';
import { Vec2f } from '../berryhunter-api/vec2f.js';


export class Input {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Input {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInput(bb:flatbuffers.ByteBuffer, obj?:Input):Input {
  return (obj || new Input()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInput(bb:flatbuffers.ByteBuffer, obj?:Input):Input {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Input()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tick():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

movement(obj?:Vec2f):Vec2f|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec2f()).__init(this.bb_pos + offset, this.bb!) : null;
}

rotation():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

action(obj?:Action):Action|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Action()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

activeAuraSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : -1;
}

static startInput(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTick(builder:flatbuffers.Builder, tick:bigint) {
  builder.addFieldInt64(0, tick, BigInt('0'));
}

static addMovement(builder:flatbuffers.Builder, movementOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, movementOffset, 0);
}

static addRotation(builder:flatbuffers.Builder, rotation:number) {
  builder.addFieldFloat32(2, rotation, 0.0);
}

static addAction(builder:flatbuffers.Builder, actionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, actionOffset, 0);
}

static addActiveAuraSlot(builder:flatbuffers.Builder, activeAuraSlot:number) {
  builder.addFieldInt8(4, activeAuraSlot, -1);
}

static endInput(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
