// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ItemStack {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ItemStack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

item():number {
  return this.bb!.readUint8(this.bb_pos);
}

count():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

slot():number {
  return this.bb!.readUint8(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createItemStack(builder:flatbuffers.Builder, item: number, count: number, slot: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.pad(3);
  builder.writeInt8(slot);
  builder.writeInt32(count);
  builder.pad(3);
  builder.writeInt8(item);
  return builder.offset();
}

}
