// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ActionType } from '../berryhunter-api/action-type.js';


export class OngoingAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OngoingAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

ticksRemaining():number {
  return this.bb!.readUint16(this.bb_pos);
}

actionType():ActionType {
  return this.bb!.readUint8(this.bb_pos + 2);
}

item():number {
  return this.bb!.readUint8(this.bb_pos + 3);
}

static sizeOf():number {
  return 4;
}

static createOngoingAction(builder:flatbuffers.Builder, ticks_remaining: number, action_type: ActionType, item: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt8(item);
  builder.writeInt8(action_type);
  builder.writeInt16(ticks_remaining);
  return builder.offset();
}

}
