// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AABB } from '../berryhunter-api/aabb.js';
import { EntityType } from '../berryhunter-api/entity-type.js';
import { StatusEffect } from '../berryhunter-api/status-effect.js';
import { Vec2f } from '../berryhunter-api/vec2f.js';


export class Placeable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Placeable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlaceable(bb:flatbuffers.ByteBuffer, obj?:Placeable):Placeable {
  return (obj || new Placeable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlaceable(bb:flatbuffers.ByteBuffer, obj?:Placeable):Placeable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Placeable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

entityType():EntityType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : EntityType.DebugCircle;
}

statusEffects(index: number):StatusEffect|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

statusEffectsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

statusEffectsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

pos(obj?:Vec2f):Vec2f|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec2f()).__init(this.bb_pos + offset, this.bb!) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

item():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

aabb(obj?:AABB):AABB|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new AABB()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startPlaceable(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addEntityType(builder:flatbuffers.Builder, entityType:EntityType) {
  builder.addFieldInt16(1, entityType, EntityType.DebugCircle);
}

static addStatusEffects(builder:flatbuffers.Builder, statusEffectsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, statusEffectsOffset, 0);
}

static createStatusEffectsVector(builder:flatbuffers.Builder, data:StatusEffect[]):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startStatusEffectsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addPos(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, posOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldInt16(4, radius, 0);
}

static addItem(builder:flatbuffers.Builder, item:number) {
  builder.addFieldInt8(5, item, 0);
}

static addAabb(builder:flatbuffers.Builder, aabbOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, aabbOffset, 0);
}

static endPlaceable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
