// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Character } from '../berryhunter-api/character.js';
import { Spectator } from '../berryhunter-api/spectator.js';


export enum Player {
  NONE = 0,
  Character = 1,
  Spectator = 2
}

export function unionToPlayer(
  type: Player,
  accessor: (obj:Character|Spectator) => Character|Spectator|null
): Character|Spectator|null {
  switch(Player[type]) {
    case 'NONE': return null; 
    case 'Character': return accessor(new Character())! as Character;
    case 'Spectator': return accessor(new Spectator())! as Spectator;
    default: return null;
  }
}

export function unionListToPlayer(
  type: Player, 
  accessor: (index: number, obj:Character|Spectator) => Character|Spectator|null, 
  index: number
): Character|Spectator|null {
  switch(Player[type]) {
    case 'NONE': return null; 
    case 'Character': return accessor(index, new Character())! as Character;
    case 'Spectator': return accessor(index, new Spectator())! as Spectator;
    default: return null;
  }
}
