// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ServerMessageBody, unionToServerMessageBody, unionListToServerMessageBody } from '../berryhunter-api/server-message-body.js';


export class ServerMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerMessage(bb:flatbuffers.ByteBuffer, obj?:ServerMessage):ServerMessage {
  return (obj || new ServerMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerMessage(bb:flatbuffers.ByteBuffer, obj?:ServerMessage):ServerMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bodyType():ServerMessageBody {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ServerMessageBody.NONE;
}

body<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startServerMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBodyType(builder:flatbuffers.Builder, bodyType:ServerMessageBody) {
  builder.addFieldInt8(0, bodyType, ServerMessageBody.NONE);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bodyOffset, 0);
}

static endServerMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createServerMessage(builder:flatbuffers.Builder, bodyType:ServerMessageBody, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServerMessage.startServerMessage(builder);
  ServerMessage.addBodyType(builder, bodyType);
  ServerMessage.addBody(builder, bodyOffset);
  return ServerMessage.endServerMessage(builder);
}
}
