// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SpendSkillPoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SpendSkillPoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpendSkillPoint(bb:flatbuffers.ByteBuffer, obj?:SpendSkillPoint):SpendSkillPoint {
  return (obj || new SpendSkillPoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpendSkillPoint(bb:flatbuffers.ByteBuffer, obj?:SpendSkillPoint):SpendSkillPoint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SpendSkillPoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

skillId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

unspend():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSpendSkillPoint(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSkillId(builder:flatbuffers.Builder, skillId:number) {
  builder.addFieldInt16(0, skillId, 0);
}

static addUnspend(builder:flatbuffers.Builder, unspend:boolean) {
  builder.addFieldInt8(1, +unspend, +false);
}

static endSpendSkillPoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSpendSkillPoint(builder:flatbuffers.Builder, skillId:number, unspend:boolean):flatbuffers.Offset {
  SpendSkillPoint.startSpendSkillPoint(builder);
  SpendSkillPoint.addSkillId(builder, skillId);
  SpendSkillPoint.addUnspend(builder, unspend);
  return SpendSkillPoint.endSpendSkillPoint(builder);
}
}
