// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StatusEffect {
  Damaged = 0,
  Yielded = 1,
  Freezing = 2,
  Starving = 3,
  Regenerating = 4,
  DamagedAmbient = 5
}
