// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Welcome {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Welcome {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWelcome(bb:flatbuffers.ByteBuffer, obj?:Welcome):Welcome {
  return (obj || new Welcome()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWelcome(bb:flatbuffers.ByteBuffer, obj?:Welcome):Welcome {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Welcome()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

serverName():string|null
serverName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
serverName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mapRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

totalDaycycleTicks():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

dayTimeTicks():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startWelcome(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addServerName(builder:flatbuffers.Builder, serverNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, serverNameOffset, 0);
}

static addMapRadius(builder:flatbuffers.Builder, mapRadius:number) {
  builder.addFieldFloat32(1, mapRadius, 0.0);
}

static addTotalDaycycleTicks(builder:flatbuffers.Builder, totalDaycycleTicks:bigint) {
  builder.addFieldInt64(2, totalDaycycleTicks, BigInt('0'));
}

static addDayTimeTicks(builder:flatbuffers.Builder, dayTimeTicks:bigint) {
  builder.addFieldInt64(3, dayTimeTicks, BigInt('0'));
}

static endWelcome(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWelcome(builder:flatbuffers.Builder, serverNameOffset:flatbuffers.Offset, mapRadius:number, totalDaycycleTicks:bigint, dayTimeTicks:bigint):flatbuffers.Offset {
  Welcome.startWelcome(builder);
  Welcome.addServerName(builder, serverNameOffset);
  Welcome.addMapRadius(builder, mapRadius);
  Welcome.addTotalDaycycleTicks(builder, totalDaycycleTicks);
  Welcome.addDayTimeTicks(builder, dayTimeTicks);
  return Welcome.endWelcome(builder);
}
}
