/**
 * The skill-VFX facts the Visuals section needs and Go does not export: the
 * body stems a layer may name, and the colours the engine will draw a layer in
 * (plan-skill-vfx.md §12f.5 C3b, piece B).
 *
 * `api/skill-fx/bodies.json` is GENERATED by `node tools/make-skill-fx-manifest.mjs`
 * from the PNG stems in `frontend/src/features/skill-fx/assets/bodies/`; it is
 * the list Go refuses an unknown `body` against, so the body picker offers
 * exactly it. An empty or unreadable list THROWS: a silently empty body picker
 * is the worse failure (the readSkillIcons posture).
 *
 * `frontend/src/features/skill-fx/logic/SkillFxPalette.ts` holds the colour
 * rule's hexes in TypeScript only. ⚑ Parsed, not imported: this tool has no
 * build step. The parse is scoped to the `DAMAGE_TYPE_COLORS` block and the
 * `NEUTRAL_COLOR` line, and it THROWS when the parsed keys are not exactly the
 * vocabulary fixture's `damageTypes`: the editor's twin of
 * `SkillFxPalette.test.ts`, so a new damage type without a colour is loud here
 * as well as in the frontend suite.
 *
 * ⚑ NODE ONLY (it reads files). The browser gets both as `skillFxBodies` and
 * `skillFxPalette` on /api/data.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { readSkillVocabulary } from './vocabulary.mjs';

export const SKILL_FX_BODIES_FILE = path.join('api', 'skill-fx', 'bodies.json');
export const SKILL_FX_BODIES_DIR = path.join('frontend', 'src', 'features', 'skill-fx', 'assets', 'bodies');
export const SKILL_FX_PALETTE_FILE = path.join('frontend', 'src', 'features', 'skill-fx', 'logic', 'SkillFxPalette.ts');

export const REGEN_BODIES = 'node tools/make-skill-fx-manifest.mjs';

const PALETTE_OPEN = 'DAMAGE_TYPE_COLORS: Record<string, number> = {';
const PALETTE_ENTRY = /^\s*([a-z_]+):\s*0x([0-9a-fA-F]{6}),?\s*$/;
const NEUTRAL_LINE = /^export const NEUTRAL_COLOR = 0x([0-9a-fA-F]{6});/m;

/** The body stems a layer may name, in manifest order. */
export function readSkillFxBodies(root) {
  const abs = path.join(root, SKILL_FX_BODIES_FILE);
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(abs, 'utf8'));
  } catch (err) {
    throw new Error(`cannot read ${abs} (${err.message}) - it is a GENERATED file, regenerate it with: ${REGEN_BODIES}`);
  }
  const bodies = manifest?.bodies;
  if (!Array.isArray(bodies) || bodies.length === 0 || !bodies.every((b) => typeof b === 'string' && b !== '')) {
    throw new Error(`${abs} carries no body list - regenerate it with: ${REGEN_BODIES}`);
  }
  return bodies;
}

/**
 * The palette as `{ damageTypes: { fire: '#ff7a1a', ... }, neutral: '#e8e8e8' }`,
 * lowercase `#rrggbb`. Throws when the block or the neutral line is missing,
 * or when the parsed keys are not exactly the fixture's damage types.
 */
export function readSkillFxPalette(root) {
  const abs = path.join(root, SKILL_FX_PALETTE_FILE);
  const src = readFileSync(abs, 'utf8');

  const lines = src.split('\n');
  const start = lines.findIndex((line) => line.includes(PALETTE_OPEN));
  if (start < 0) throw new Error(`${abs} has no "${PALETTE_OPEN}" block - the palette's shape changed and this parser needs updating`);
  const damageTypes = {};
  let closed = false;
  for (const line of lines.slice(start + 1)) {
    if (line.trim() === '};') { closed = true; break; }
    const m = PALETTE_ENTRY.exec(line);
    if (m) damageTypes[m[1]] = `#${m[2].toLowerCase()}`;
  }
  if (!closed) throw new Error(`${abs}: the DAMAGE_TYPE_COLORS block never closes with "};"`);

  const neutral = NEUTRAL_LINE.exec(src);
  if (!neutral) throw new Error(`${abs} has no "export const NEUTRAL_COLOR = 0x......;" line`);

  const expected = [...readSkillVocabulary(root).damageTypes].sort();
  const parsed = Object.keys(damageTypes).sort();
  if (JSON.stringify(parsed) !== JSON.stringify(expected)) {
    throw new Error(`${abs}: DAMAGE_TYPE_COLORS names [${parsed.join(', ')}], but the vocabulary's damageTypes are [${expected.join(', ')}] - every damage type needs exactly one colour`);
  }
  return { damageTypes, neutral: `#${neutral[1].toLowerCase()}` };
}
