#!/usr/bin/env node
/**
 * Packs the PONETI icons Aura uses into texture atlases and publishes them into
 * the frontend build output. A BUILD STEP: package.json runs it after
 * `npm run build` (postbuild, because webpack.prod.js wipes dist/ first) and
 * before `npm run start`.
 *
 *   node tools/pack-icons.mjs                 # the build step
 *   node tools/pack-icons.mjs --self-test     # exercises every path on a fake pack, no licence needed
 *
 * Input:  frontend/src/client-data/icons/pack-manifest.json  (committed: name -> path in the pack)
 *         $AURA_ICON_PACK_DIR/<path>                          (the raw pack, NEVER in the repo)
 * Built:  frontend/icons-prebuilt/atlas-<hash>.png             (one or more 2048² sheets, LOCAL, gitignored)
 *         frontend/icons-prebuilt/icons.json                   (name -> {atlas, x, y, w, h}, plus atlasSize/iconSize)
 * Served: frontend/dist/icons/                                 (a copy of the prebuilt set, made on every run)
 *
 * Two steps, and only the first needs the pack:
 *   1. BUILD, AURA_ICON_PACK_DIR set (the seat holder): pack the manifest into
 *      frontend/icons-prebuilt/. Fails, naming the fix, when the folder is
 *      missing, when a manifest entry has no file (all listed at once), when a
 *      source is not 256×256, or when the manifest is malformed.
 *   2. PUBLISH, always: copy frontend/icons-prebuilt/ to frontend/dist/icons/,
 *      so `npm run build` wiping dist/ never needs the pack again. With no
 *      prebuilt set (every clone but the seat holder's, while the atlases stay
 *      out of git: THIRD_PARTY.md) it writes an empty lookup, prints one notice
 *      line and exits 0: the game then draws the glyphs and the committed
 *      portraits.
 *
 * Deterministic: entries sort by name, so the same manifest and pack give the
 * same bytes, and the atlas file name is the content hash of the sheet.
 */
import {copyFileSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, unlinkSync, writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import os from 'node:os';
import path from 'node:path';
import {
    ATLAS_FILE, ATLAS_SIZE, ENV_PACK_DIR, GUTTER, ICON_SIZE, LOOKUP_NAME, MANIFEST_PATH, OUT_DIR, PREBUILT_DIR, ROOT,
    layoutGrid, readManifest, rel, resolvePackDir, sha256,
} from './icon-pack-common.mjs';

// sharp lives under frontend/node_modules (a declared devDependency there).
const sharp = createRequire(path.join(ROOT, 'frontend/package.json'))('sharp');

function parseArgs(argv) {
    const opts = {manifest: MANIFEST_PATH, out: OUT_DIR, prebuilt: PREBUILT_DIR, pack: undefined, selfTest: false};
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--self-test') opts.selfTest = true;
        else if (a === '--manifest') opts.manifest = path.resolve(argv[++i]);
        else if (a === '--out') opts.out = path.resolve(argv[++i]);
        else if (a === '--prebuilt') opts.prebuilt = path.resolve(argv[++i]);
        else if (a === '--pack') opts.pack = path.resolve(argv[++i]);
        else throw new Error(`unknown argument ${a}`);
    }
    return opts;
}

function writeLookup(outDir, lookup) {
    mkdirSync(outDir, {recursive: true});
    writeFileSync(path.join(outDir, LOOKUP_NAME), JSON.stringify(lookup, null, 2) + '\n');
}

function removeStaleAtlases(outDir) {
    if (!existsSync(outDir)) return;
    for (const name of readdirSync(outDir)) {
        if (ATLAS_FILE.test(name)) unlinkSync(path.join(outDir, name));
    }
}

/**
 * Step 2: copy the prebuilt set (lookup + the atlases it names) into the served
 * directory, or an empty lookup when there is no prebuilt set to copy.
 */
function publish(prebuilt, out, log) {
    const lookupFile = path.join(prebuilt, LOOKUP_NAME);
    removeStaleAtlases(out);
    if (!existsSync(lookupFile)) {
        log(`🖼  icons: no prebuilt set at ${rel(prebuilt)}/ and ${ENV_PACK_DIR} is not set: this build has no pack icons. See README "Icons (PONETI pack)".`);
        writeLookup(out, {_comment: `GENERATED by tools/pack-icons.mjs without a prebuilt set or ${ENV_PACK_DIR}: no pack icons in this build.`, iconSize: ICON_SIZE, atlasSize: ATLAS_SIZE, atlases: [], icons: {}});
        return {atlases: [], icons: 0};
    }
    const lookup = JSON.parse(readFileSync(lookupFile, 'utf8'));
    mkdirSync(out, {recursive: true});
    for (const atlas of lookup.atlases) {
        copyFileSync(path.join(prebuilt, atlas), path.join(out, atlas));
    }
    copyFileSync(lookupFile, path.join(out, LOOKUP_NAME));
    return {atlases: lookup.atlases, icons: Object.keys(lookup.icons).length};
}

export async function pack({manifest = MANIFEST_PATH, out = OUT_DIR, prebuilt = PREBUILT_DIR, pack, env = process.env, log = console.log} = {}) {
    const entries = readManifest(manifest);

    if (!pack && !env[ENV_PACK_DIR]) {
        const published = publish(prebuilt, out, log);
        if (published.atlases.length > 0) {
            log(`🖼  icons: ${published.icons} prebuilt icon(s) in ${published.atlases.length} atlas(es) copied from ${rel(prebuilt)}/ to ${rel(out)}/ (${entries.length} in the manifest; repacking needs ${ENV_PACK_DIR}).`);
        }
        return {...published, skipped: true};
    }

    const packDir = resolvePackDir(pack, env);

    const missing = entries.filter(({file}) => !existsSync(path.join(packDir, file)));
    if (missing.length > 0) {
        throw new Error(
            `${missing.length} manifest icon(s) not found under ${ENV_PACK_DIR}=${packDir}:\n` +
            missing.map(({name, file}) => `  ${name} -> ${file}`).join('\n') +
            `\nFix the path in ${rel(manifest)} or check the pack export.`);
    }

    const sources = [];
    for (const {name, file} of entries) {
        const abs = path.join(packDir, file);
        const meta = await sharp(abs).metadata();
        if (meta.width !== ICON_SIZE || meta.height !== ICON_SIZE) {
            throw new Error(`${name} -> ${file} is ${meta.width}×${meta.height}, the pack format is ${ICON_SIZE}×${ICON_SIZE}`);
        }
        sources.push({name, file, buffer: await sharp(abs).ensureAlpha().png().toBuffer()});
    }

    const {cells, atlasCount} = layoutGrid(sources.length, {atlasSize: ATLAS_SIZE, iconSize: ICON_SIZE, gutter: GUTTER});
    const atlasNames = [];
    const sheets = [];
    for (let a = 0; a < atlasCount; a++) {
        const composites = [];
        cells.forEach((cell, i) => {
            if (cell.atlas === a) composites.push({input: sources[i].buffer, left: cell.x, top: cell.y});
        });
        const sheet = await sharp({
            create: {width: ATLAS_SIZE, height: ATLAS_SIZE, channels: 4, background: {r: 0, g: 0, b: 0, alpha: 0}},
        }).composite(composites).png({compressionLevel: 9}).toBuffer();
        sheets.push(sheet);
        atlasNames.push(`atlas-${sha256(sheet).slice(0, 12)}.png`);
    }

    removeStaleAtlases(prebuilt);
    mkdirSync(prebuilt, {recursive: true});
    sheets.forEach((sheet, a) => writeFileSync(path.join(prebuilt, atlasNames[a]), sheet));

    const icons = {};
    sources.forEach(({name}, i) => {
        const {atlas, x, y, w, h} = cells[i];
        icons[name] = {atlas: atlasNames[atlas], x, y, w, h};
    });
    writeLookup(prebuilt, {
        _comment: 'GENERATED by tools/pack-icons.mjs from pack-manifest.json - do not hand-edit, do not commit (THIRD_PARTY.md).',
        iconSize: ICON_SIZE,
        atlasSize: ATLAS_SIZE,
        atlases: atlasNames,
        icons,
    });
    publish(prebuilt, out, log);
    log(`🖼  icons: ${sources.length} packed into ${atlasCount} atlas(es) at ${rel(prebuilt)}/, copied to ${rel(out)}/`);
    return {atlases: atlasNames, icons: sources.length, skipped: false};
}

// ---------------------------------------------------------------------------
// Self-test: a throwaway pack of solid-colour PNGs in a temp dir. Runs without
// the licensed pack, so it works on CI and on a fresh clone.
async function selfTest() {
    const tmp = mkdtempSync(path.join(os.tmpdir(), 'aura-icon-pack-'));
    const packDir = path.join(tmp, 'pack');
    const out = path.join(tmp, 'out');
    const prebuilt = path.join(tmp, 'prebuilt');
    const manifest = path.join(tmp, 'manifest.json');
    const quiet = () => {};
    let passed = 0;
    const ok = (label) => { passed++; console.log(`  PASS ${label}`); };
    const expectThrow = async (label, fn, needle) => {
        try {
            await fn();
        } catch (error) {
            if (!String(error.message).includes(needle)) {
                throw new Error(`${label}: error did not mention "${needle}": ${error.message}`);
            }
            ok(label);
            return;
        }
        throw new Error(`${label}: expected a failure mentioning "${needle}"`);
    };
    const solid = (r, g, b, size = ICON_SIZE) =>
        sharp({create: {width: size, height: size, channels: 4, background: {r, g, b, alpha: 255}}}).png().toBuffer();

    try {
        // A fake pack: 70 icons in a nested folder, so two 2048² atlases at 7×7 = 49 per sheet.
        mkdirSync(path.join(packDir, 'Icons/Potions'), {recursive: true});
        const icons = {};
        for (let i = 0; i < 70; i++) {
            const file = `Icons/Potions/Icon_Potion_${String(i).padStart(2, '0')}.png`;
            writeFileSync(path.join(packDir, file), await solid(i * 3, 255 - i * 3, 40));
            icons[`potion-${String(i).padStart(2, '0')}`] = file;
        }
        writeFileSync(manifest, JSON.stringify({icons}));

        const result = await pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet});
        if (result.atlases.length !== 2) throw new Error(`expected 2 atlases, got ${result.atlases.length}`);
        const lookup = JSON.parse(readFileSync(path.join(out, LOOKUP_NAME), 'utf8'));
        const built = JSON.parse(readFileSync(path.join(prebuilt, LOOKUP_NAME), 'utf8'));
        if (JSON.stringify(built) !== JSON.stringify(lookup)) throw new Error('served lookup differs from the prebuilt one');
        for (const atlas of result.atlases) {
            if (!existsSync(path.join(prebuilt, atlas)) || !existsSync(path.join(out, atlas))) throw new Error(`${atlas} missing from prebuilt or out`);
        }
        ok('atlases are built into the prebuilt dir and copied to the served dir');
        if (lookup.atlasSize !== ATLAS_SIZE || lookup.iconSize !== ICON_SIZE) throw new Error('lookup lacks atlasSize/iconSize');
        const p00 = lookup.icons['potion-00'];
        const p49 = lookup.icons['potion-49'];
        if (p00.x !== 0 || p00.y !== 0 || p00.atlas !== result.atlases[0]) throw new Error(`potion-00 landed at ${JSON.stringify(p00)}`);
        if (p49.atlas !== result.atlases[1] || p49.x !== 0 || p49.y !== 0) throw new Error(`potion-49 should open atlas 2 at 0,0, got ${JSON.stringify(p49)}`);
        const p08 = lookup.icons['potion-08'];
        if (p08.x !== ICON_SIZE + GUTTER || p08.y !== ICON_SIZE + GUTTER) throw new Error(`potion-08 should sit at row 1 col 1, got ${JSON.stringify(p08)}`);
        ok('70 icons -> 2 atlases, grid coordinates as laid out');

        // The pixel under potion-08's cell carries its colour: the composite really happened.
        const px = await sharp(path.join(out, p08.atlas)).extract({left: p08.x + 5, top: p08.y + 5, width: 1, height: 1}).raw().toBuffer();
        if (px[0] !== 24 || px[1] !== 231 || px[2] !== 40 || px[3] !== 255) throw new Error(`potion-08 pixel is ${[...px]}`);
        const gutter = await sharp(path.join(out, p08.atlas)).extract({left: p08.x - 1, top: p08.y + 5, width: 1, height: 1}).raw().toBuffer();
        if (gutter[3] !== 0) throw new Error(`gutter pixel is not transparent: ${[...gutter]}`);
        ok('atlas pixels match the source, gutter is transparent');

        // Determinism: a second run produces the same atlas names.
        const again = await pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet});
        if (again.atlases.join() !== result.atlases.join()) throw new Error('atlas hashes changed between identical runs');
        if (readdirSync(out).filter((n) => ATLAS_FILE.test(n)).length !== 2) throw new Error('stale atlases were not removed');
        if (readdirSync(prebuilt).filter((n) => ATLAS_FILE.test(n)).length !== 2) throw new Error('stale prebuilt atlases were not removed');
        ok('byte-stable across runs, stale sheets removed');

        // No pack, but the prebuilt set is there (every clone but the seat holder's): served as is.
        rmSync(out, {recursive: true, force: true});
        const fromPrebuilt = await pack({manifest, out, prebuilt, env: {}, log: quiet});
        if (!fromPrebuilt.skipped || fromPrebuilt.atlases.join() !== result.atlases.join() || fromPrebuilt.icons !== 70) throw new Error(`prebuilt set not published: ${JSON.stringify(fromPrebuilt)}`);
        if (readdirSync(out).filter((n) => ATLAS_FILE.test(n)).length !== 2) throw new Error('prebuilt atlases were not copied');
        ok(`unset ${ENV_PACK_DIR} publishes the local prebuilt set`);

        // No pack and no prebuilt set: an empty lookup, no atlases, exit 0.
        const unset = await pack({manifest, out, prebuilt: path.join(tmp, 'no-prebuilt'), env: {}, log: quiet});
        const unsetLookup = JSON.parse(readFileSync(path.join(out, LOOKUP_NAME), 'utf8'));
        if (!unset.skipped || unsetLookup.atlases.length !== 0 || Object.keys(unsetLookup.icons).length !== 0) throw new Error('unset pack dir without a prebuilt set should write an empty lookup');
        if (readdirSync(out).some((n) => ATLAS_FILE.test(n))) throw new Error('unset pack dir left atlases behind');
        ok(`unset ${ENV_PACK_DIR} without a prebuilt set writes an empty lookup, removes stale sheets, exits 0`);
        await expectThrow('missing pack dir fails', () => pack({manifest, out, prebuilt, env: {[ENV_PACK_DIR]: path.join(tmp, 'nope')}, log: quiet}), 'does not exist');

        writeFileSync(manifest, JSON.stringify({icons: {...icons, 'ghost-a': 'Icons/Missing_A.png', 'ghost-b': 'Icons/Missing_B.png'}}));
        await expectThrow('missing manifest entries are all listed', () => pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet}), 'ghost-a -> Icons/Missing_A.png\n  ghost-b -> Icons/Missing_B.png');

        writeFileSync(path.join(packDir, 'Icons/odd.png'), await solid(1, 2, 3, 128));
        writeFileSync(manifest, JSON.stringify({icons: {odd: 'Icons/odd.png'}}));
        await expectThrow('wrong source size fails', () => pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet}), '128×128');

        writeFileSync(manifest, JSON.stringify({icons: {'Bad Name': 'Icons/odd.png'}}));
        await expectThrow('malformed name fails', () => pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet}), 'must match');
        writeFileSync(manifest, JSON.stringify({icons: {esc: '../outside.png'}}));
        await expectThrow('path escaping the pack fails', () => pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet}), 'relative path inside the pack');

        writeFileSync(manifest, JSON.stringify({icons: {}}));
        const empty = await pack({manifest, out, prebuilt, pack: packDir, env: {}, log: quiet});
        if (empty.atlases.length !== 0 || empty.icons !== 0) throw new Error('empty manifest should pack nothing');
        ok('empty manifest packs nothing but still needs the pack dir');

        console.log(`pack-icons self-test: ${passed} PASS / 0 FAIL`);
    } finally {
        rmSync(tmp, {recursive: true, force: true});
    }
}

// Always dispatches: nothing imports this file, and a "main module" guard that
// mis-compares paths would let a build step pass having packed nothing.
const opts = parseArgs(process.argv.slice(2));
(opts.selfTest ? selfTest() : pack(opts)).catch((error) => {
    console.error(`✖ pack-icons: ${error.message}`);
    process.exit(1);
});
